### ISSUE TITLE
Unable to connect ibeam with paper login IBKR

### ISSUE THREAD

**Issue by Riyaz84** [Voyz/ibeam#101]
Hi Voyzan, 

Users of IBeam, i would like to know if it possible to use IBeam with paper account with interactive brokers ? thanks 

Regards,

**Comment by Voyz** [comment]
Hey @Riyaz84 thanks for outlining your issue 🙂

Yes, it is possible to use IBeam with paper account. You simply need to use your paper account credentials from IBKR, instead of the live trading ones. 

See here: https://ibkr.info/node/663

**Comment by Riyaz84** [comment]
Hi Voyzan,

Thanks for your reply, once after the setup of IBeam on my server, as in attach, i don't have any option to select paper trading account, from the webportal. Thanks.

Regards,



<img width="665" alt="ibeam login" src="https://user-images.githubusercontent.com/17121106/191230243-1f5a1800-03fc-4334-b9df-d0d6415daf85.png">

**Comment by Voyz** [comment]
Please get in touch with IBKR support for info on how to get your paper trading account details 👍

**Comment by Riyaz84** [comment]
Already got one, the question is where to use paper login credentials on the localhost IBeam web portal ?  Thanks

**Comment by jimrobinson** [comment]
The paper trading account has a unique login, distinct from your live trading account.   So if you use the paper trading account name and associated password, it should log  you into the paper trading account.  At least that's the way I've seen it work.  As a made up example, someone might have a live trading account name of johndoe37 and a paper trading account name of johnva721.

**Comment by jimrobinson** [comment]
If you log into IB you ought to be able to navigate to the account icon (torso and head icon), then click on Settings.  Under Account Configuration there is a Paper Trading Account link next the Paper Trading Account Number. Click on the Paper Trading Account link.  It should bring up a page detailing the Paper Trading Username.

**Comment by Riyaz84** [comment]
Thanks for that clarification, it seems there are two different user accounts Live/Demo, and the demo account password need to be reset. Works fine. Thanks
