### ISSUE TITLE
Add usage examples

### ISSUE THREAD

**Issue by stanj98** [Voyz/ibeam#102]
- Prerequisites required before setting up IBEAM (screenshots will be provided)
    - IBKR gateway portal folder
    - Docker
    - Java (doubts about demonstrating this but it’s necessary for IBKR gateway to
work)
- Once the above are installed, clone IBEAM
- Provide example on running docker instance
    - Provide screenshot of terminal
- Provide example on setting up standalone script (optional)
- Code examples on reading info from IBKR
- Maybe provide potential logger file to keep logs of data (if there is already one, then
ignore this)
- SSL certificates (later stage)
- 2FA (later stage)

**Comment by stanj98** [comment]
@Voyz, let me know if there are any other type of examples you wish to provide, thanks.

**Comment by Voyz** [comment]
Hey @stanj98 thanks for sharing your ideas to add the examples, great contribution!

I appreciate you followed the bug reporting template in this issue, however given its nature I think we can avoid using this template with sections, and simply start by copy pasting the outline that you've sent me over email. Could you do that, and we can work from there?

**Comment by stanj98** [comment]
Sure @Voyz, check now and let me know.

**Comment by Voyz** [comment]
Right, so I'd suggest staring with breaking it down to two setups:

1. Docker image
2. Standalone

Starting with the Docker image, as it is simpler to set up:

- Have a Docker installed
- Prepare credentials
- Pull the IBeam image
- Start the image
- Verify that it is working using a simple request

Now, for Standalone, we'd need:

- Java, Gateway, chromedriver, chrome, Python
- Prepare credentials
- Running the `ibeam_starter.py`
- Verify that it is working using a simple request

Advanced examples we leave for a later date.
