### ISSUE TITLE
Deploying ibeam to Azure with docker compose

### ISSUE THREAD

**Issue by TermITx** [Voyz/ibeam#104]
Hi,

I'm trying to deploy IBEAM to Azure in a multi-container app.  The first container is IBEAM, and the second is my API which uses IBEAM for authentication.

docker-compose.yaml:

> services:
>   app:
>     image: termitx/test
>     network_mode: "service:ibeam"
>     depends_on:
>       - ibeam
>   ibeam:
>     image: voyz/ibeam
>     ports:
>       - "5000:5000"
>       - "80:8000"
>     environment:
>       IBEAM_ACCOUNT: ACC
>       IBEAM_PASSWORD: PW

This works perfectly on my computer, but since Azure doesn't allow port mapping (as described [here](https://learn.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#docker-compose-options) ), I can't get it working. 
Is there a workaround for this problem?

Thanks in advance.

**Comment by Voyz** [comment]
Hey @TermITx thanks for outlining your issue in detail 👍

Unfortunately, I don't know how that could be achieved as I don't use Azure, I'd suggest positing on Azure-related forums or subreddits. Good luck!

**Comment by Voyz** [comment]
I'm going to close this issue due to lack of activity. Feel free to reopen if you'd like to continue the discussion 👍 Thanks for participating!
