### ISSUE TITLE
Verbose the logs

### ISSUE THREAD

**Issue by Riyaz84** [Voyz/ibeam#105]
Hello, 

Nothing relevant on the logs, Is it possible to verbose more on the logs in order to check, each returns of the command curl ? 

2022-09-23 20:02:31,294|I| Gateway running and authenticated
2022-09-23 20:03:31,299|I| Gateway running and authenticated
2022-09-23 20:04:31,306|I| Gateway running and authenticated
2022-09-23 20:05:31,306|I| Gateway running and authenticated
2022-09-23 20:06:31,306|I| Gateway running and authenticated

Thanks

**Comment by Riyaz84** [comment]
Also, i would like to know if it possible to get the response an API query on the log ? Thanks

**Comment by Voyz** [comment]
Hey @Riyaz84 thanks for asking, good question!

IBeam only makes sure the Gateway starts and is authenticated, but doesn't capture any traffic going to the Gateway - therefore there is nothing that it could display. You'd want to look at the logs that the Gateway generates that should be stored in the Gateway's directory - either locally on your system or in the Docker container.

If you'd like to get more verbosity on the functionality of IBeam itself, you can set the `IBEAM_LOG_LEVEL` env var to `DEBUG` - see the wiki for more: https://github.com/Voyz/ibeam/wiki/IBeam-Configuration

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
