### ISSUE TITLE
Set account number in environment variable

### ISSUE THREAD

**Issue by MislavSag** [Voyz/ibeam#106]
I have user with 2 pape accounts. Every account has it's own account number. Is it possible to set account number as environment variable when running the docker image.

For example, if IB accounts are:

user: ibuser1
pass: pass12345
account_number: DU6103078

user: ibuser1
pass: pass12345
account_number: DU6103158

How I can run ibeam with DU6103158 (sub)account instead of DU6103078 (master account.)

**Comment by Voyz** [comment]
Hey @MislavSag thanks for using IBeam and outlining your issue 😊

I'm not entirely sure if I understand what you're asking for - as you only need to provide account name and account password to authenticate. Try providing that account_number as the account name in the two instances of IBeam and see if that solves your issue.

**Comment by MislavSag** [comment]
Sorry, I have discovered the question doesn't have much sense.

I have to set master account and than, wen sending request I can send account ID for specific endpoint. For exmaple, I authenticate wih master paper account and then place orders for different subaccount with account id argument.
