### ISSUE TITLE
SSL: certificate subject name (Client Portal Web API) does not match target host name

### ISSUE THREAD

**Issue by MislavSag** [Voyz/ibeam#107]
I successfully deployed `voyz/ibeam` image to the Azure Container instance.

When I send requests from the local machine, everything works as expected.

Then I created an R plumber API endpoint that uses the same code. But when I deploy API on the server, it returns an error:
```
Error in curl::curl_fetch_memory(url, handle = handle): SSL: certificate subject name (Client Portal Web API) does not match target host name 'gazdekdu5890012.germanywestcentral.azurecontainer.io'
```
Why do I get the above error when I deploy the API to Azure (as I said, the same endpoint doesn't return an error when executed locally).

**Comment by MislavSag** [comment]
Ihave found the solution. I have to set curl option `ssl_verifyhost` to FALSE (not just `ssl_verifypeer`).

**Comment by Voyz** [comment]
Hey @MislavSag glad to see you managed to resolve your issue, thanks for posting the answer back in here 😊👏
