### ISSUE TITLE
 File/Directory exception during log creation in logs.py when running in Container mode

### ISSUE THREAD

**Issue by chaltik** [Voyz/ibeam#108]
Describe the bug
When running in standalone (i.e: non-Docker container), the logs.py file generates an exception when trying to create the log file

To Reproduce

docker run --env-file ibeam_env.list -p 5000:5000 voyz/ibeam

Expected behavior:
Normal operation

Environment
IBeam version: Latest
Docker image or standalone: Docker image
OS: Ubuntu 20.04

Additional context
![image](https://user-images.githubusercontent.com/16768683/193306134-06359600-9d79-4ec6-ae7b-cf3bb8d1d168.png)

**Comment by chaltik** [comment]
Additional information: the above error appears even if the said file exists (I did `touch ibeam_log__2022-10-01.txt`).
![image](https://user-images.githubusercontent.com/16768683/193432074-6a1ae551-9b20-4694-b414-b8955af1aee0.png)

**Comment by Voyz** [comment]
Hey @chaltik thanks for providing the screenshots and all the info. 

Could I ask you to run IBeam in [debug mode](https://github.com/Voyz/ibeam/wiki/IBeam-Configuration) (set `IBEAM_LOG_LEVEL` to `DEBUG`) and pasting the whole output of the IBeam log here? I suspect the `OUTPUTS_DIR` may be set to `/home/karen/dev/irobot/ibeam_outputs/` which is a directory on your local machine but not within the container.

**Comment by chaltik** [comment]
i added the debug variable to the environment but it didn't have any effect on the output. You are correct that my IBEAM_OUTPUTS_DIR is set to the value you identified. Should I not set that value in the environment list and let docker image to default to internal one?
![image](https://user-images.githubusercontent.com/16768683/194206677-9b218182-a1b0-4c26-98ed-3ab6604cce98.png)

**Comment by chaltik** [comment]
i removed it just to see what happens and i got a different error message, so it's progress:
![image](https://user-images.githubusercontent.com/16768683/194206980-8deba88d-11e0-4744-be4c-3c9005c27f24.png)

**Comment by Voyz** [comment]
Thanks @chaltik - now, these variables all need to be paths inside the container, not within your host machine. You want to mount these paths to your container as volumes: https://docs.docker.com/storage/bind-mounts/

Eg. `-v /home/karen/dev/irobot/irobot/../ibeam_inputs:/srv/inputs`

The syntax is
`-v [HOST_PATH]:[CONTAINER_PATH]`

**Comment by chaltik** [comment]
Thanks. I have added the two -v options, but perhaps incorrectly? or do i need to map some of the other paths as well
![image](https://user-images.githubusercontent.com/16768683/195241393-2b39a003-627c-4158-b795-fe8de01f85fb.png)

**Comment by Voyz** [comment]
Right, so what I wrote about container/host paths is true for all the other paths too - chrome driver, gateway, etc. You'd need to change these too. 

Also, it seems that there is a permissions issue with the path you're mounting on the host - I'd suggest to try a different path

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
