### ISSUE TITLE
Docker fails to start due to port address conflict

### ISSUE THREAD

**Issue by avatariq** [Voyz/ibeam#111]
I am unable to initiate voyz/ibeam docker run, because the default port conflicts with an existing port in my system. I am not aware of a work around. It would be nice if there is an option to auto switch to another open port and ask the user to use this port. I understand that IB gateway runs on a default port but that can be changed in the configuration settings of the gateway.
[GIT Issue_voyz_ibeam.docx](https://github.com/Voyz/ibeam/files/9824377/GIT.Issue_voyz_ibeam.docx)
I got an error trying to drag and drop an attachment. In case it did not attach. Here is raw text of the attachment:
GIT Issue:voyz/ibeam
I am unable to run voyz/ibeam docker image due to this error:
docker run --env env.list -p 5000:5000 voyz/ibeam                              
docker: Error response from daemon: driver failed programming external connectivity on endpoint lucid_pascal
(2c1e7653e6c0e4550e754492cd523ee7c15e2cb83207b82ca1fd1c2762bbbed3): Error starting userland proxy: listen tcp
4 0.0.0.0:5000: bind: address already in use.
 
Find out who is using this port:
 ~/New Projects/ibeam_test $>   
sudo lsof -i -P -n | grep 5000
[sudo] password for thasnain:  
docker-re 1063 docker-registry    6u  IPv6  26913      0t0  TCP *:5000 (LISTEN)
~/New Projects/ibeam_test $>  
 
Here is the config yaml for registry
  
cat config.yml  
version: 0.1
log:
 fields:
   service: registry
storage:
 cache:
   blobdescriptor: inmemory
 filesystem:
   rootdirectory: /var/lib/docker-registry
 delete:
   enabled: true
http:
 addr: :5000
 headers:
   X-Content-Type-Options: [nosniff]
auth:
 htpasswd:
   realm: basic-realm
   path: /etc/docker/registry
health:
 storagedriver:
   enabled: true
   interval: 10s
   threshold: 3
 
  
Tried using docker compose method 
cat docker-compose
version: "2.1"
 
services:
 ibeam:
   image: voyz/ibeam
   container_name: ibeam
   env_file:
     - env.list
   ports:
     - 5000:5000
     - 5001:5001
   network_mode: bridge # Required due to clientportal.gw IP whitelist
   restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
 
 
 
docker-compose up -d
Starting ibeam ...
Starting ibeam ... error
 
ERROR: for ibeam  Cannot start service ibeam: driver failed programming external connectivity on endpoint ibeam (5c241fcc9d293545c31e30e8d79ade9f7d981fefdb2fc2a90295478f5207d963): Error starting userland proxy: listen tcp4 0.0.0.0:631: bind: address already in use
 
ERROR: for ibeam  Cannot start service ibeam: driver failed programming external connectivity on endpoint ibeam (5c241fcc9d293545c31e30e8d79ade9f7d981fefdb2fc2a90295478f5207d963): Error starting userland proxy: listen tcp4 0.0.0.0:631: bind: address already in use
ERROR: Encountered errors while bringing up the project.
Wed Oct 19 03:12 PM  ~/New Projects/ibeam_test $>

**Comment by avatariq** [comment]
I filed this issue. I missed to mention that I changed the port number in docker compose and tried again. The docker compose is therefore different and hence the error is about port:631
cat docker-compose.yml
version: "2.1"

services:
ibeam:
image: voyz/ibeam
container_name: ibeam
env_file:
- env.list
ports:
- 631:5000
- 631:5001
network_mode: bridge # Required due to clientportal.gw IP whitelist
restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded

The same error occurs for port 5000. Issue remains the same.

**Comment by jimrobinson** [comment]
I think the problem you have with your 631 port attempt was that you re-used the same external port.  Try using two different port mappings, e.g.,

* 631:5000
* 632:5001

The internal ports (5000, 5001) should never have any conflict with your host, and so you just need two available host ports.

**Comment by Voyz** [comment]
Hey @avatariq thanks for posting your issue and providing all the details 😊

If 5000 is taken on your machine you should be able to remap it. As @jimrobinson pointed out (thanks for chipping in Jim 👍), that second time you seemed to try to map two ports into one port on the host. 

Alternatively, you can change the default port the gateway is listed on by modifying the conf.yaml file: https://github.com/Voyz/ibeam/wiki/Gateway-Configuration

Let us know how it goes

**Comment by avatariq** [comment]
Hi Voyz/Jim,
Thanks for your guidance. Changed the port numbers as Jim suggested. Initially it did not work, but then I used a port number above 5000 and that seemed to work. I no longer get an error anymore. I have not had a chance to do much yet, but will be actively learning the platform. Thanks very much for your support. This issue can be closed now.

**Comment by Voyz** [comment]
Glad to hear it worked, well done @avatariq  👍
