### ISSUE TITLE
Query about ibkr login and logout

### ISSUE THREAD

**Issue by raj-crec** [Voyz/ibeam#112]
Is user login and logout on ibkr accomplished through 'start' and 'stop' of the relevant user container ??
I am using 1 container for each user of my system ...

**Comment by Voyz** [comment]
Hey @raj-crec thanks for your question 👍

To start with - IBeam wasn't built with a functionality of logging users out in mind. It was meant to log the user in and keep it logged in.

However, in practice yeah, starting the container can be thought of as 'logging in', and stopping the container as 'logging out'.

Hope that helps!

**Comment by raj-crec** [comment]
Yup it does .. thanks for the clarification !
