### ISSUE TITLE
Query: Memory footprint of multiple ibeam containers

### ISSUE THREAD

**Issue by raj-crec** [Voyz/ibeam#113]
Hi,

I have 10 users in my system, who fire trades independently using IBKR.
I have 10 ibeam containers on my server, 1 for each of the users.

What are the memory implications of this scenario ? How many containers can run seamlessly on my AWS server ( approx. ) ? Is there any such limitation in the first place ?

**Comment by Voyz** [comment]
Hey @raj-crec good question! There's no data currently on how much memory does IBeam consume. If you'd like to conduct such study, please make sure to share your results here 😉 You could run a simple script to measure the memory available before and after IBeam is used on your host - this should be a good place to start.

As for deploying 10 containers on an AWS server - that's certainly possible, provided that your server has sufficient resources to do so. This isn't intrinsic to IBeam in any way. 

I've seen other users using multiple IBeam instances, so theoretically this should be doable. Just make sure you map the ports accordingly to avoid conflicts 👍

**Comment by raj-crec** [comment]
Thanks much ... I'll update if we do the memory test anytime soon !

**Comment by HaSiMiPa** [comment]
few datapoints from running iBeam on my local NAS (a Synology with 4GB RAM). 
Each iBeam instance consumes 0.1% CPU load and 140 (+/- 5) MB RAM. These values are stable over at least a 14 days period.
I do run 4 instances and I could likely run 10+.
