### ISSUE TITLE
How to run 2 docker containers on one system?

### ISSUE THREAD

**Issue by AmitKehat** [Voyz/ibeam#115]
Hello,

I tried to run 2 docker containers on one system.
The first one loaded, connected and authenticated as expected.
For the second one, I tried to follow the instractions under "Changing port" section:
1. Modify listenPort value in conf.yaml, eg: listenPort: 8000
2. Provide environment variable IBEAM_GATEWAY_BASE_URL with a URL modified to the port we want to set, eg: IBEAM_GATEWAY_BASE_URL=https://localhost:8000
3. Run IBeam, mapping the new port, eg. docker run -p 8000:8000

First, I was not sure how to provide to the docker container the environment variable IBEAM_GATEWAY_BASE_URL. Shoukd it be part of the docker run command? configuration file?

Second, the command I use to run the image for the first container:
docker run -v /root/inputs/:/srv/inputs --env-file env.list -p 5000:5000 voyz/ibeam

The command I use to run the image for the second container:
docker run -v /root/inputs/:/srv/inputs --env-file env.list -p 6000:6000 voyz/ibeam

After running the second command, I am trying to load the login page in the browser, but getting "This site can’t be reached" message.

What am I missing?

Thanks,
Amit

**Comment by investudiollc** [comment]
First, you need to have two different accounts (login and password) for IB.
Next create two files env_1.list and env_2.list.
Then run two different gateway using one image:
First
docker container run -d --env-file env_1.list --restart=always --name ibeam_1 -p 5000:5000 voyz/ibeam:latest
Second
docker container run -d --env-file env_2.list --restart=always --name ibeam_2 -p 5001:5000 voyz/ibeam:latest

**Comment by freekeys** [comment]
Should this be 5002:5000 or instead 5002:5002?

**Comment by investudiollc** [comment]
> Should this say 5002:5000 or instead 5002:5002? I guess it's a typo?

This is not a typo, but a real example that I use.

**Comment by Voyz** [comment]
hey @freekeys thanks for describing your issue 👍

Thanks @investudiollc for chipping in, your advise is correct.

@freekeys you write:

>After running the second command, I am trying to load the login page in the browser,

You don't need to load the login page in the browser. That's exactly what IBeam should handle for you. Both terminals you launch from should provide you logging information on whether the two sessions were automatically authenticated correctly. Can you check for these?

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
