### ISSUE TITLE
Session Authentication Issue

### ISSUE THREAD

**Issue by vlpraveen** [Voyz/ibeam#117]
Hi

Installed ibeam client web portal on a remote Debian Linux Server (Server A) and successfully did 2FA Login.
I am then able to then call all the APIs and get the desired results from my local machine which I used for logging in.

Now, if I call the same APIs from an another server (Server B), I get the following error message
{"error":"Init session first","statusCode":400}

The tickle api when called from my local machine to Server A has the Json 'authenticated' field set to true but if the same api is called from Server B to Server A, the 'authenticated' field is set to 'false'.

Output of Authentication Status API when called from my local machine to Server A:
{
	"authenticated": true,
	"competing": false,
	"connected": true,
	"message": "",
	"MAC": "XX:XX:XX:XX:XX:XX",
	"serverInfo": {
		"serverName": "XXXXX",
		"serverVersion": "Build 10.20.0a, Nov 16, 2022 8:12:50 PM"
	},
	"fail": ""
}

Output of Authentication Status API when called from Server B to Server A:
{
"authenticated":false,
"competing":false,
"connected":false,
"MAC":"XX:XX:XX:XX:XX:XX"
}

My question is when the docker session is already authenticated, why I am not able to call the same api from a different server to the docker server ?

Sorry is there something too basic which I am missing ? How do we make this work ? Ideally I want to call the apis from Server B and not from my local machine

**Comment by Voyz** [comment]
Hey @vlpraveen thanks for highlighting your issue in detail 👍

Wow, that's indeed unexpected. Can you share what endpoints are you calling in both cases? The output you provide has different format in both cases, so I'm wondering if it's the same endpoint that is being called

**Comment by vlpraveen** [comment]
Hey @Voyz 

Steps to reproduce:

1. Start Docker Run in Server A
2. Complete the 2FA authentication Login from your local machine
3. Check if Docker gateway is running and authenticated in Server A
4. Now curl GET the end point _https://<Server_A_IP>:5000/v1/api/iserver/auth/status_ from Server A or from your local machine which you used to authenticate. Both the curl output gives the desired results with 'authenticated' json field set to 'true'
5. Now SSH to a different server. Say Server B. Now curl GET the end point _https://<Server_A_IP>:5000/v1/api/iserver/auth/status_. This time the curl output gives the result but the 'authenticated' json field is 'false'

If authenticated is false, your session won't be able to call any meaningful endpoints such as get market data or place order etc.

Regards
Praveen

**Comment by Voyz** [comment]
Thanks for providing more details @vlpraveen 👍

I hate to say this but... it works on my end 😅 A sad joke I know, let's try to find out how we can help you.

In my case I started `voyz/ibeam:latest` on Server A on GCP, then called:

```
curl -X GET "https://localhost:5000/v1/api/iserver/auth/status" -k
``` 
which produced:

```
{"authenticated":true,"competing":false,"connected":true,"message":"","MAC":"XXXX","serverInfo":{"serverName":"XXXX","serverVersion":"Build 10.19.0f, Nov 3, 2022 11:16:49 AM"},"fail":""}
```



Then SSH'd to Server B and called:

```
curl -X GET "https://INTERNAL_IP_OF_SERVER_A:5000/v1/api/iserver/auth/status" -k
```
which also produced:


```
{"authenticated":true,"competing":false,"connected":true,"message":"","MAC":"XXXX","serverInfo":{"serverName":"XXXX","serverVersion":"Build 10.19.0f, Nov 3, 2022 11:16:49 AM"},"fail":""}
```

----

Can you share which IBeam version are you running and how do you deploy your servers? Which cloud?

**Comment by vlpraveen** [comment]
Thanks for the detailed explanation @Voyz 

Couple of questions: 

How was the 2FA authentication done when you started voyz/ibeam on Server A ? Did you open the browser from your local machine and authenticated ?

How to find the version of the iBeam ? I am running in linode

**Comment by Voyz** [comment]
@vlpraveen I've run it on paper trading account, so no 2FA, but I wouldn't think that should matter in this particular case.

I've not opened the browser from a local machine. I've started two virtual machines on GCP - one running IBeam, the other one from which I sent the requests.

 > How to find the version of the iBeam ? I am running in linode
 
IBeam should print that in its startup logs. Additionally if you're running it as a Docker image it's the image version you're running - `latest` if you haven't specified anything.

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
