### ISSUE TITLE
Automatic Re-Authentication

### ISSUE THREAD

**Issue by freemanc-007** [Voyz/ibeam#118]
Hi Voy,

I am in the process of getting my software connected to my live account, as I have been testing with the paper trading account so far.  With the paper trading account, when there was an internet disruption (I am running on an LTE network), I would be issued a new public IP address from the LTE supplier.  I have had confirmation from Interactive Brokers before, that when the public IP address changes, I have to re-authenticate.  In my software, it was s simple case of closing the Docker instance of the IBeam connection, and then creating a new one.

However, with the 2 Factor Authentication (2FA) required by Interactive Brokers for live accounts, this process doesn’t work.  So I have implemented your Google Messages solution to give Ibeam the code generated in the 2FA process.  One thing I have noted, the time-out environment variable at default value was too short, I increased it to “IBEAM_PAGE_LOAD_TIMEOUT=6000” which now works reliably.

I then tested a network disruption by unplugging the power to the router for 30 seconds or so and plugging it back in again.  The following was noted in the log file:

2022-11-29 08:39:44,813|D| Maintenance
2022-11-29 08:39:44,814|D| HTTPS (unverified) request to: https://localhost:4002/v1/api/tickle
2022-11-29 08:39:45,087|I| Gateway running and authenticated
2022-11-29 08:40:44,813|D| Maintenance
2022-11-29 08:40:44,814|D| HTTPS (unverified) request to: https://localhost:4002/v1/api/tickle
2022-11-29 08:40:45,067|I| Gateway running and authenticated
2022-11-29 08:41:44,813|D| Maintenance
2022-11-29 08:41:44,814|D| HTTPS (unverified) request to: https://localhost:4002/v1/api/tickle
2022-11-29 08:42:04,151|E| Connection timeout after 15 seconds. Consider increasing timeout by setting IBEAM_REQUEST_TIMEOUT environment variable. Error: The read operation timed out
2022-11-29 08:42:04,151|I| No active sessions, logging in...
2022-11-29 08:42:04,152|D| Loading auth webpage at https://localhost:4002/sso/Login?forwardTo=22&RL=1&ip2loc=on
Execution of job "GatewayClient._maintenance (trigger: interval[0:01:00], next run at: 2022-11-29 08:42:44 UTC)" skipped: maximum number of running instances reached (1)
Execution of job "GatewayClient._maintenance (trigger: interval[0:01:00], next run at: 2022-11-29 08:43:44 UTC)" skipped: maximum number of running instances reached (1)
Execution of job "GatewayClient._maintenance (trigger: interval[0:01:00], next run at: 2022-11-29 08:44:44 UTC)" skipped: maximum number of running instances reached (1)
Execution of job "GatewayClient._maintenance (trigger: interval[0:01:00], next run at: 2022-11-29 08:45:44 UTC)" skipped: maximum number of running instances reached (1)

This just continued and IBeam didn’t manage to re-authenticate.  You have mentioned that IBeam is supposed to manage the re-connection, so wondering what is happening here?

Kind regards,
Charles
[2FA - 04.txt](https://github.com/Voyz/ibeam/files/10129641/2FA.-.04.txt)

**Comment by freemanc-007** [comment]
Just a bit more info on 2FA, I logged a help ticket asking if it can be disabled.  This is their response:

"There is no means to disable Two Factor Authentication. There is also no means to belay the query as the Web API authentication key resets every 24 hours, which can not be altered. There is no "work around" in this case.

And while the two factor is currently not required for paper trading accounts, I can not speak to the future of that behavior. All I can say is that I am not aware of any plans to change this behavior. "

**Comment by Voyz** [comment]
Hey @freemanc-007 thanks for outlining your issue in detail 👍

From what I understand the following happens:

1. You set the IBEAM_PAGE_LOAD_TIMEOUT to 6000 seconds, which is 100 minutes, about 1.666 hours.
2. You allow IBeam to authenticate
3. You disconnect the internet
4. IBeam fails to complete a request (due to no internet), and starts the reauthentication
5. IBeam fails to load the authentication page (due to no internet)
6. IBeam waits for 1.666 hours before reattempting

This would explain why you're seeing the output you're seeing. If the IBEAM_PAGE_LOAD_TIMEOUT was smaller, IBeam would reattempt sooner.

I think we'd want to look into why you needed to raise the IBEAM_PAGE_LOAD_TIMEOUT to such a high value. What exactly happens when you keep it at the default?

**Comment by freemanc-007** [comment]
Hi Voy,

I had a situation where the login page seemed to not be fast enough and I had assumed increasing this variable would allow for a slower internet connection.  
I'd set the value to 6000 seconds as an arbitrary high number as a result, I hadn't realized this would affect the re-attempt!  I've now set it to 30 seconds and tried short internet disruptions (a few seconds just to give me a new public IP address and cause Interactive Brokers to disconnect the authentication), and IBeam sucsessfuly re-authenticates.

I tried a longer disruption of approximately 1 minute (long enough for IBeam to fail a tickle) and IBeam successfully re-authenticates.

I then tried a longer disruption of 20 minutes, I was expecting IBeam to give up after 10 attempts (which would have been within the 20 minutes), but instead, about 5 minutes in, it just stopped.  I had assumed it was frozen.  I left the 20 minute interval of no internet to complete and then re-established the internet connection, and IBeam then displayed all the attempts of authenticate in one go in the log.  Not sure what would cause the log display to not update during this period?  I left it for a few minutes and when trying to copy the log text, it updated again in a batch.  It successfully re-authenticated though!

If I may make a general suggestion, not sure if it is relevant, before trying to make a connection to Interactive Brokers, to first ping www.google.com to check that there is a connection to the outside world?  Then at least there is no possibility of reaching the 10 authentication steps before IBeam exits.  Although, there were approximately 20 connection attempts in the log, which is more than the default 10, so is it checking internet irrespective and not accumulating an attempt towards the 10 if there is no internet?

Thank you for all your hard work on this amazing product!

Kind regards,
Charles

**Comment by Voyz** [comment]
Thanks for a detailed outline of what happened. Glad to see that lowering that value have helped 👍

You speak of these 10 attempts after which you'd expect for things to stop - where did you get this number? Are you referring to `IBEAM_MAX_IMMEDIATE_ATTEMPTS` env var? That counter only gets bumped if IBKR returns an error, which we know that would lead to an account lockout. You can read more about it here: https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#authentication-retries. Or you're talking about the lockout after 10 failed attempts described in the section below that one?

In either case, connectivity issues when loading the page are not counting towards the lockout, therefore IBeam will continue reauthenticating indefinitely - which is what its principle purpose is: to regain authentication as soon as possible upon events such as this one.

Thanks for your suggestion too, although - unless I'm wrong - whether we ping google.com (which is a nice idea anyway, we could do nevertheless) or IBKR login page is irrelevant; I think that both operations succeed and fail in the same way if we are/aren't connected to the internet. And, as mentioned above, failing to reach IBKR webpage doesn't contribute to the lockout counter, therefore we can just continue doing so.

It is strange that you stopped seeing logs after a while, though intuitively that sounds like some output buffer issue. If you've got some time (and will) could you try doing this once/twice more to see if that's a reproducible behaviour?

And many thanks for the kind words, happy to see IBeam is being used and recognised 😊

**Comment by freemanc-007** [comment]
Yes, I was referring to the IBEAM_MAX_IMMEDIATE_ATTEMPTS variable.  But it is good to see that the lockout attempts are only counted when a response is received from Interactive Brokers, so yes, the pinging google is not necessary.  I will gladly do more testing on the log display and report back here today.

**Comment by Voyz** [comment]
Fantastic @freemanc-007 glad to hear it helped 👍 And thanks for reporting on the lag, it's good to know it was just an one-off 😊 Are you okay to close this issue at this point?

**Comment by freemanc-007** [comment]
I think it's safe to close it, thanks, if the problem pops up with repeated circumstances I'll document it and log a new issue.
