### ISSUE TITLE
How to configure SMS as 2FA method?

### ISSUE THREAD

**Issue by rubenbriones** [Voyz/ibeam#119]
Hello,

I'm trying to use `ìbeam` with my real account, but for the moment I couln't be able to bypass 2FA, as I don't receive any SMS code. Instead I receive a push notification in mi mobile phone, or a code challenge to enter in IBKR mobile app.

It is possible to change the IB account configuration to set the 2FA method to be SMS code? There is any way to disable IB Key app, once it have been configured?

I have been looking in every IB settings/help how to disbale it, but I could not figure out. My current `Scure Login System` is set to IB Key and I don't know how to change it. Anyone knows how to solve it, to be able to use the `IBEAM_TWO_FA_HANDLER=GOOGLE_MSG`, please?

Thank you very much in advance.

**Comment by rubenbriones** [comment]
Hey Voyz, yes it is an IB configuration. I just wanted to know if there was any way to disable it. But seems that is not possible. IB support have just answered my ticket with the next response:

_"SMS two-factor authentication is considered as temporary as it is enabled once you verify the phone number provided during the account application process. Hence, it is not possible to revert receiving the security code via SMS once activated a permanent security device."_

So, it seems that once activated the IB Key is not possible to disable it.

Do you have any idea if it would be possible to workaround this 2FA method? 

My only "idea" is if the IB 24-hour disconnect can be set, in the API Client, to be done always at the same hour (as can be configured in the TWS). And set it to an hour in which we are pretty sure that we would be able to touch the IB Key notification in our mobile phone.... and hope that there is no additional external disconnection. ¿Anyone have a better workaround?

Thanks you so much for your help!

**Comment by Voyz** [comment]
Thanks for reporting back what you've heard from IBRK - that's very useful. 

Your idea could work - how about you set a cron job on whatever system you're running IBeam on, that would stop and restart the container on a 24-hour interval, at whichever hour you find convenient?

**Comment by rubenbriones** [comment]
Okey, thanks for the crontab idea Voyz, I will test it!

One question only, the days that I have tested IBeam docker image, I have been logged-out at 00:00 Europe/Madrid (my current timezone), without had being logged for more than 24 hours (my login was 2-3 before, around 21:00-22:00). I suppose that this logout is due to the 24h rule, but do you know it for sure? Do you know if the 24h logout is always at this time, or it can depend on the IB account/user, or any other circunstance?

Thanks in advance!

**Comment by Voyz** [comment]
Sorry, I wish I could help but no idea on when do they log out. I'd contact IBKR support for more info on this 👍

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
