### ISSUE TITLE
How to verify cacert.pem from another server?

### ISSUE THREAD

**Issue by dariozac** [Voyz/ibeam#123]
Trying to call `requests.get("https://localhost:5000/v1/api/portfolio/accounts", verify='cacert.pem')` from another server using the IP address of the ibeam instead of localhost of course - all was working when verify=False before i installed the TLS certificates.

I am using fastApi with the following  as an example

@app.get("/getAccounts")
async def get_accounts():
    r = requests.get(
        "https://XX.XXX.XX.XX:5000/v1/api/portfolio/accounts", verify="cacert.pem")
    return json(r.text)

i tried various places to put the cacert in my server folder and tried web searches.

**Comment by dariozac** [comment]
**Describe the bug**
I would like my ibeam instance that is deployed on a Debian server (AWS EC2) to receive GET and POST requests from another server

**To Reproduce**
Steps to reproduce the behavior:
1. Fresh Install of iBeam Docker
2. Follow instructions on https://github.com/Voyz/ibeam/wiki upto and including [TLS Certificates and HTTPS](https://github.com/Voyz/ibeam/wiki/TLS-Certificates-and-HTTPS)
3. make a test request to see all is working `curl -X GET "https://localhost:5000/v1/api/portfolio/{ACCOUNT_NUM}/positions" --cacert inputs/cacert.pem`
4. Make a similar request from another service (white listed)
5. See error:
 `Max retries exceeded with url: /v1/api/pa/performance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))`

**Expected behavior**
I expected to get a response.

**Environment**
IBeam version: 
Docker image or standalone: Docker
Python version (standalone users only):
OS: debian 11

**Additional context**
Add any other context about the problem here.

**Suggest a Fix**
It appears to be a CACERT issue (I am not an expert)
From the terminal i tried using the following to find my CACERT path and file on both the server issuing the request and my local PC
'from requests.utils import DEFAULT_CA_BUNDLE_PATH`
`print(DEFAULT_CA_BUNDLE_PATH)'`

`import certifi`
`certifi.where()`

Then using `requests.get("https://localhost:5000/v1/api/portfolio/accounts", verify='/etc/ssl/certs/cacert.pem')`

the path i found from 

python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests.utils import DEFAULT_CA_BUNDLE_PATH
>>> print(DEFAULT_CA_BUNDLE_PATH)
/etc/ssl/certs/ca-certificates.crt

I am not an expert in cacerts so any help or advice hughely appreciated and if I am way off track.

Finally thank you to everyone who is working on this valuable project

**Comment by Voyz** [comment]
Thanks for providing more info @dariozac 

Are you supplying that same cacert when starting IBeam? Could you share your docker command when starting up IBeam, or its cloud configuration?

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
