### ISSUE TITLE
Connection keeps dropping

### ISSUE THREAD

**Issue by muu1994** [Voyz/ibeam#127]
Hello, do you know why connection keeps dropping?
I'm running latest ibeam docker and using live account with 2FA /IBKey app/. 
I had to complete authentication over and over again.
Attached a screenshot.
![Capture](https://user-images.githubusercontent.com/82366429/214495627-1b828f42-ddc9-42b6-98b6-4148895e2b4b.JPG)

**Comment by alderaan** [comment]
For me it keeps dropping every few days. And I have to log into the website and log out and restart the gateway docker image. It's so super annoying. I just still can't believe that IB let's this happen and there seems to be no solution.

**Comment by kls06541** [comment]
Feel you pain , I have to do the same thing daily

**Comment by Voyz** [comment]
Hey @muu1994 thanks for submitting your issue 👍

Unfortunately, this seems to be a reoccurring issue with IBKR - their authentication is not predictable and not stable. IBeam does its best to maintain the Gateway authenticated, so whenever it notices a lack of authentication it will attempt to reauthenticate. 

Some users reported that logging into TWS or IBKR website caused the authentication on the Gateway to drop.

I'd suggest for you to report that to IBKR support, as to let them know how much of a burning issue this is for their algo trading community.
