### ISSUE TITLE
The API data is not returned in first attempt

### ISSUE THREAD

**Issue by kadnan** [Voyz/ibeam#128]
Which ever API endpoint I hit, it does not return on first attempt, as you can see here. What is the reason and how to deal with it for a production system?

<img width="861" alt="Screenshot 2023-01-26 at 9 11 20 PM" src="https://user-images.githubusercontent.com/273196/214893835-94f83c1b-f8a2-40fc-bdd3-7c725c387034.png">

**Comment by Voyz** [comment]
Hey @kadnan thanks for outlining this issue.

IBeam doesn't does not interrupt or intercept the requests made to the Gateway in any way. I'd suggest highlighting this problem with IBKR support.

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
