### ISSUE TITLE
CORS issue in browser

### ISSUE THREAD

**Issue by jussirantala** [Voyz/ibeam#129]
**Describe the bug**
Cannot fetch any of the APIs from my browser because: `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I have the default conf.yaml which has the following setting:
`cors:
    origin.allowed: "*"`

Doesn't it mean it should allow my request from my browser?

The requests are fine because I am able to get responses if I use a reverse proxy in between which doesn't care about CORS or certs. However I am building a platform for other people to use and requiring to run a reverse proxy would suck.

**Comment by Voyz** [comment]
Hey @jussirantala thanks for describing your issue 👍

When you say 

> Cannot fetch any of the APIs from my browser

What do you mean exactly? How are you calling these APIs?

The Gateway should be usable without a reverse proxy.

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍

**Comment by Voyz** [comment]
@cmmartin I was told by IBKR support to use this extension when trying to test the API from the browser:

https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf

**Comment by cmmartin** [comment]
Okay thanks for the response. I will just build a simple reverse proxy instead
