### ISSUE TITLE
SMS Instead of Fingerprints

### ISSUE THREAD

**Issue by kls06541** [Voyz/ibeam#135]
Hello everyone,

I'm hoping someone can help me with implementing IBEAM with fingerprint verification. I have the same concern as many others - I only have access to fingerprint verification and I'm not sure how to go about implementing IBEAM.

I'm aware that SMS verification is an option, but I'm not sure how to get it. Does anyone have any advice on how to get started to be approved by IBKR for SMS verification? 

Any guidance would be greatly appreciated.

Thank you in advance!

**Comment by Voyz** [comment]
Hey @kls06541 I'd suggest you talk to IBKR support and see if they can change your 2FA type. What what I understand - although that's just my observation, not information I got from IBKR - which 2FA is available depends on the country you're registered from

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍
