### ISSUE TITLE
Looking for docker run on Raspberry 

### ISSUE THREAD

**Issue by Enigma-song** [Voyz/ibeam#136]
I tried to download the docker to my Raspberry, it showed as below:
docker pull voyz/ibeam
Using default tag: latest
latest: Pulling from voyz/ibeam
no matching manifest for linux/arm/v8 in the manifest list entries

Wondering if we have any matching docker file?

**Comment by Voyz** [comment]
Hey @Enigma-song thanks for reporting your issue 👍

The latest tag is built for both AMD/ARM 64, you can see the two versions in the Docker Hub: https://hub.docker.com/layers/voyz/ibeam/latest/images/sha256-d4f4a9d2d780851df2bab10fabb95da6b26c4b57a72d2ff8eaefefb9c1153ac6?context=repo

I've tried building for `linux/arm/v8` however the build process keep on failing and I cannot figure out what the problem may be. Feel free to look into building the image yourself and updating the build process for IBeam if you manage to succeed 👍

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to reopen if you'd like to continue the discussion 👍

**Comment by matthewmoorcroft** [comment]
Hi, reopening this as the current docker container doesn't support armv7 which I need for my RP3B, I have forked to see if I could build for it and I have managed to do it successfully, it did require the installation of more libraries to the dockerfile as well as the installation of Rust to be able to install pillow.

These were the libraries required to build successfully `pkg-config libssl-dev  libffi-dev zlib1g-dev libjpeg-dev `

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
