### ISSUE TITLE
Login attempts dont clear previous input

### ISSUE THREAD

**Issue by JackD111** [Voyz/ibeam#144]
**Describe the bug**
For some reason today, ibeam had to re-auth and failed to login. After restarting it, it worked again.
I checked the logs and had the following:

![image](https://github.com/Voyz/ibeam/assets/3951120/db38fc6a-ebb5-40ec-bee3-d0a8566f94f5)

I looked at the created PNGs and noticed, that the username and password kept repeating in the inputs for each successive re-try, essentially adding to the name and password instead of replacing the existing values

**Expected behavior**
Re-load the login page before attempting a new login or clear the inputs

**Environment**
IBeam version: voyz/ibeam:latest (0.4.5)
Docker image or standalone: docker
OS: linux

**Comment by Voyz** [comment]
Hey @JackD111 thanks for submitting this issue and sharing all the details 👍

That is very well spotted, I'm ashamed this bug hid out here for so long 🙈 

I've added `.clear()` to all input fields where we input text. I've pushed `voyz/ibeam:0.4.6-rc4` with that fix, let me know if it helps.

**Comment by JackD111** [comment]
Thank you, appreicate the fast update. I'll run the new image version and report back, if there are issues.

**Comment by Voyz** [comment]
Hey @JackD111 just pushed `0.4.6` as latest, closing this issues as completed. Feel free to continue the discussion if necessary though.
