### ISSUE TITLE
Login Steps

### ISSUE THREAD

**Issue by migoohao** [Voyz/ibeam#146]
I have tried the 0.4.6-rc3, but it still did not work well. So I open a new Issue to talk about this.

I noticed IBeam did not check '/v1/api/iserver/auth/status' endpoint during the first login attempt. 
'/v1/api/iserver/auth/status' is a very important endpoint, we can use this to decide if we need to load auth webpage or just trigger the reauthenticate endpoint.

If '/v1/api/iserver/auth/status' return HTTP code 401, we need to load auth webpage.
If '/v1/api/iserver/auth/status' return HTTP code 200 but authenticated: false, we need to trigger the reauthenticate endpoint. And reauthenticate need about 15 seconds to be completed. The best way to check if reauthenticate is finished: check '/v1/api/iserver/auth/status' every second until HTTP code 200 and authenticated: true. Sometimes after 15 seconds wait, authentication is still false. In this case, we do not need to load auth webpage, just trigger reauthenticate again.  Or after several times reauthenticate, the authenticated field is still false, load auth webpage again.

PS: Loading auth webpage is an expensive way, it will trigger 'Two-Factor Authentication'. We should do this only if '/v1/api/iserver/auth/status' return HTTP code 401.

Here is the start-up log with my explanation(those bold ones). 
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo#/
2023-06-22 03:46:00,118|D| HTTPS (unverified) request to: https://localhost:5000
2023-06-22 03:46:00,914|I| Gateway connection established
2023-06-22 03:46:00,915|D| HTTPS (unverified) request to: https://localhost:5000/v1/portal/sso/validate
2023-06-22 03:46:01,153|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-06-22 03:46:01,378|I| No active sessions, logging in...
2023-06-22 03:46:01,378|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
2023-06-22 03:46:09,505|D| Elements: {'USER_NAME_EL': 'username', 'PASSWORD_EL': 'password', 'SUBMIT_EL': 'button.btn.btn-lg.btn-primary', 'ERROR_EL': 'xyz-errormessage', 'SUCCESS_EL_TEXT': 'Client login succeeds', 'IBKEY_PROMO_EL_CLASS': 'ibkey-promo-skip', 'TWO_FA_EL_ID': 'twofactbase', 'TWO_FA_NOTIFICATION_EL': 'login-step-notification', 'TWO_FA_INPUT_EL_ID': 'chlginput', 'TWO_FA_SELECT_EL_ID': 'sf_select'}
2023-06-22 03:46:09,514|I| Gateway auth webpage loaded
2023-06-22 03:46:09,514|I| Login attempt number 1
2023-06-22 03:46:14,807|I| Submitting the form
2023-06-22 03:46:21,974|D| trigger: Client login succeeds
2023-06-22 03:46:21,984|I| Webpage displayed "Client login succeeds"
2023-06-22 03:46:23,985|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7f60cc18a1d0> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="abb8716170f57fd45c320fb067f8a393")>
2023-06-22 03:46:24,052|I| Authentication process succeeded
2023-06-22 03:46:27,052|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/tickle
2023-06-22 03:46:27,253|E| Gateway session active but not authenticated
2023-06-22 03:46:27,253|D| HTTPS (unverified) request to: https://localhost:5000/v1/portal/iserver/reauthenticate?force=true

**_IBeam printed this reauthenticate log, but this did not make my account authed. Then I started my App to help IBeam trigger reauthenticate, it worked again.
I just called /v1/portal/iserver/reauthenticate without param 'force=true'.
/v1/portal/iserver/reauthenticate should use http POST method, and request body should be a empty string ''._**

2023-06-22 03:46:27,278|I| Waiting 15 seconds to reauthenticate before restarting.

**_Keep checking /v1/api/iserver/auth/status in this 15 seconds._**

2023-06-22 03:46:42,278|I| Logging out and restarting the Gateway

**_I don't think we need to logout when /v1/api/iserver/auth/status return http code 200_**

2023-06-22 03:46:42,279|D| HTTPS (unverified) request to: https://localhost:5000/v1/api/logout
2023-06-22 03:46:42,499|I| Gateway logout successful

**Comment by Voyz** [comment]
Many thanks for getting into so much detail here @migoohao 👏 I've got a number of places I'd need your clarification, so let's address these:

> I noticed IBeam did not check '/v1/api/iserver/auth/status' endpoint during the first login attempt.
'/v1/api/iserver/auth/status' is a very important endpoint,

We use the tickle endpoint as it serves both as status information (providing us with `authenticated` and `competing` information) as well as a refresh, quoting the docs: _"In order to prevent the session from timing out, the endpoint /tickle should be called on a regular basis."_

If you have any information on why `/v1/api/iserver/auth/status` should be called instead of `tickle`, let us know.

> If '/v1/api/iserver/auth/status' return HTTP code 401, we need to load auth webpage.

Yes, we interpret this as 'gateway running, but no active sessions'

> If '/v1/api/iserver/auth/status' return HTTP code 200 but authenticated: false, we need to trigger the reauthenticate endpoint. 

Is advice this based on your experience, or did you get some concrete information on this? Could you link to it?

> And reauthenticate need about 15 seconds to be completed.

Again, how do you know this?

> The best way to check if reauthenticate is finished: check '/v1/api/iserver/auth/status' every second until HTTP code 200 and authenticated: true. Sometimes after 15 seconds wait, authentication is still false. In this case, we do not need to load auth webpage, just trigger reauthenticate again. Or after several times reauthenticate, the authenticated field is still false, load auth webpage again.

Now how long do we keep on pinging for status before we consider it a failure? Currently IBeam errs on the side of `authenticated: false` requiring a complete process to repeat, assuming that a fresh authentication should be the most optimal way to ensure success. Are you suggesting that doing so is not the right way to go?

I don't have arguments to claim that that your proposal is not as good as the current one, it's just different. It sounds like it would be an alternative authentication method we could implement, and let the user choose. 

> PS: Loading auth webpage is an expensive way, it will trigger 'Two-Factor Authentication'. 

Well, yes, but the assumption here is that doing 'the full thing' should be the closest to guaranteeing that it will succeed. It being 'expensive' is not that much of an issue if the likelihood of successful authentication is higher, as it only needs to happen once and takes some 10-20 seconds to complete. The reason we never used `reauthenticate` is because it never seemed to have worked as expected. At the same time, it is refreshing to see that you are getting some good results with it.

> I just called /v1/portal/iserver/reauthenticate without param 'force=true'. /v1/portal/iserver/reauthenticate should use http POST method, and request body should be a empty string ''.

Gotcha, the signature may have changed since we implemented it a while back.

> Keep checking /v1/api/iserver/auth/status in this 15 seconds.

In order to short-circuit if we see it succeed? Or why? 

> I don't think we need to logout when /v1/api/iserver/auth/status return http code 200

Logging out is what some users requested, similarly claiming that it is what helped them to reach successful authentication more often. This behaviour can be disabled by setting `IBEAM_RESTART_FAILED_SESSIONS` to False. In this case the `reauthenaticate` will be the last thing that happens until the next maintenance cycle.

**Comment by migoohao** [comment]
Thank you @Voyz for your reply. 

> If you have any information on why /v1/api/iserver/auth/status should be called instead of tickle, let us know.

1. I prefer/status because the rate limit of /status is 10req/s instead of /tickle's 1req/s. In this case, if IBeam has checked the HTTP code of /tickle, using /ticke is OK. You could check the doc of the rate limit [here](https://interactivebrokers.github.io/cpwebapi/use-cases). I know tickle is important. And IB advises us that we should tickle 1req/min at least. But I only need to check the auth status frequently, the /status endpoint is designed for this case.

> If '/v1/api/iserver/auth/status' return HTTP code 200 but authenticated: false, we need to trigger the reauthenticate endpoint.

> Is advice this based on your experience, or did you get some concrete information on this? Could you link to it?

> And reauthenticate needs about 15 seconds to be completed.

> Again, how do you know this?

2. The reason why I prefer to use /reauthenticate instead of full-step login is that I want to recover my IB Gateway auth quickly. Full-steps login is heavier than /reauthenticate. The wait time of /reauthenticate is only my experience, and IB doesn't guarantee it must reauthenticate success in the next X seconds. Sometimes it just costs 5s to reauthenticate, sometimes 10+s. This is a recovery strategy: use the quicker and easier way first, if it doesn't work, try the final method(full-step login). The most important thing is to judge if /reauthenticate may work. IB doesn't specify this, http code 200 is my experience. But HTTP code 401 tells us we have to do full-step login.
if HTTP code 200 and authenticated: false, use this strategy.
if HTTP code 401, full-steps login.
I think this strategy is not only suitable for login but also maintenance.


>Keep checking /v1/api/iserver/auth/status in these 15 seconds.

>In order to short-circuit if we see it succeed? Or why?

3. Yes, Keep checking /status in order to short-circuit if we see it successful. This can help us know if IB Gateway is ready as soon as possible.


> Logging out is what some users requested, similarly claiming that it is what helped them to reach successful authentication more often. This behavior can be disabled by setting IBEAM_RESTART_FAILED_SESSIONS to False. In this case, the reauthenticate will be the last thing that happens until the next maintenance cycle.

4. If I set IBEAM_RESTART_FAILED_SESSIONS to false, can IBean start a full-steps login when the status endpoint is 401?

**Comment by Voyz** [comment]
Hey @migoohao thanks for answering all these questions. I've given it a shot and spent a couple of days reworking things to include this new logic. I've tested it already on my setup, and I think I'm on your side now - it looks cleaner and makes more sense to me. Have a look at #147 for more details - do give it a read and see if I got your idea correctly. It would be fantastic if you could give this new version a shot too and let me know if it works for you. Many thanks for this contribution 👏

One thing I wanted to discuss outside of #147 but continue here instead, is that having evaluated the situation I've decided to stick with `/tickle` endpoint for now. The two compare as follows:

#### `/status`
* 10req/s (btw. I can't find info on this endpoint's rate limit, so I'm trusting what you wrote here)
* provides us with the following:
  * authenticated
  * competing
  * connected
  * message
  * MAC
  * serverName
  * serverVersion
  * fail

#### `/tickle`
* 1req/s
* keeps the session active
* provides us with all of the data of `/status`, plus:
  * session
  * ssoExpires
  * collission
  * user
  * hmds

My logic is as follows:

* Seeing that in the current version we never need Status updates more frequently than once a second, the rate limit advantage of `/status` is irrelevant.
* We do need to call `/tickle` [once a minute](https://interactivebrokers.github.io/cpwebapi/authentication) irrespectively of whether we want to get the Status or not. Switching to `/status` would increase complexity by having to separately call `/tickle` just to keep the authentication active.
* `/tickle` provides us with more information that can be useful

Still, if you'd have any further comments on this choice than I'm all ears.

**Comment by migoohao** [comment]
> Hey @migoohao thanks for answering all these questions. I've given it a shot and spent a couple of days reworking things to include this new logic. I've tested it already on my setup, and I think I'm on your side now - it looks cleaner and makes more sense to me. Have a look at #147 for more details - do give it a read and see if I got your idea correctly. It would be fantastic if you could give this new version a shot too and let me know if it works for you. Many thanks for this contribution 👏
> 
> One thing I wanted to discuss outside of #147 but continue here instead, is that having evaluated the situation I've decided to stick with `/tickle` endpoint for now. The two compare as follows:
> 
> #### `/status`
> * 10req/s (btw. I can't find info on this endpoint's rate limit, so I'm trusting what you wrote here)
> * provides us with the following:
>   
>   * authenticated
>   * competing
>   * connected
>   * message
>   * MAC
>   * serverName
>   * serverVersion
>   * fail
> 
> #### `/tickle`
> * 1req/s
> * keeps the session active
> * provides us with all of the data of `/status`, plus:
>   
>   * session
>   * ssoExpires
>   * collission
>   * user
>   * hmds
> 
> My logic is as follows:
> 
> * Seeing that in the current version we never need Status updates more frequently than once a second, the rate limit advantage of `/status` is irrelevant.
> * We do need to call `/tickle` [once a minute](https://interactivebrokers.github.io/cpwebapi/authentication) irrespectively of whether we want to get the Status or not. Switching to `/status` would increase complexity by having to separately call `/tickle` just to keep the authentication active.
> * `/tickle` provides us with more information that can be useful
> 
> Still, if you'd have any further comments on this choice than I'm all ears.

OK, /tickle is better than /status in this scenario.
We could talk more about v0.5.0 in another issue.
