### ISSUE TITLE
v0.5.0 - development

### ISSUE THREAD

**Issue by Voyz** [Voyz/ibeam#147]
This issue is tracking the development of [IBeam v0.5.0](https://github.com/Voyz/ibeam/tree/v0.5.0).

You can test the v0.5.0 by pulling the most recent `-rc*` tag, eg: `voyz/ibeam:0.5.0-rc1`. Go to [IBeam's Docker Hub](https://hub.docker.com/r/voyz/ibeam/tags) and check what the most recent v0.5.0 tag is.

## Major changes:

* IBeam now supports various login logic flows - we call them strategies. These can be selected by setting `IBEAM_AUTHENTICATION_STRATEGY` env var as `A` or `B`. It is possible that this is a temporary feature that will be removed once a clear winning strategy is found.
* Currently used login logic is called strategy 'A', and is used by default.
* New strategy 'B' was added, based on @migoohao's suggestions in #146. The new logic is described in detail below. This is done in an attempt to simplify the login logic and rely on `reauthenticate` more than on full re-login. Many thanks for suggesting this logic flow @migoohao 👏 I also want to give kudos to any other users who mentioned using `reauthenticate` in the past.

## New strategy 'B' logic:

See https://github.com/Voyz/ibeam/blob/v0.5.0/ibeam/src/strategy_handler.py and look for `try_authenticating` and `_authentication_strategy_B`

### Context:

Strategy 'B', just like strategy 'A', is run on every maintenance. 

Note that the result of this logic can take one of the four forms:

✅ all good - the Gateway is running and authenticated
🔐 need auth - the Gateway is running but we need to authenticate
⚠️ something's wrong - there's been some issue so we stop this authentication attempt and wait until next maintenance
🚨 shutdown - there has been a critical error during login, so we shut IBeam down

The different authentication actions that can be taken are:

* _login_ - perform a "full" login, using the web form.
* _reauthenticate_ - perform a reauthentication by calling 'reauthenticate' endpoint. This requires a _login_ to have already happened.
* _logout_ - perform a logout by calling the 'logout' endpoint. This, somehow, will not invalidate the session, so we can still _reauthenticate_ afterwards.

### The logic is described below:

_(this is subject to change)_

1. Check Status. In short, 'checking Status' is a call to `tickle` endpoint that refreshes the session and provides us with a bunch of information on the Gateway, the current session and our authentication status. Note that Status now contains additional information ([see source](https://github.com/Voyz/ibeam/blob/v0.5.0/ibeam/src/http_handler.py)).
2. If `authenticated` and `not competing`: ✅ all good
3. if `not running`: ⚠️ something's wrong - we can't communicate with the Gateway, so we won't attempt authentication.

Above steps are the exact same for strategy 'A' and strategy 'B'. The following is where strategy 'B' differs:

1. if `not session`: 🔐 need auth - there is a running Gateway but it has no active session, so we _login_ using the web form
2. elif `not connected` or `competing`: 🔐 need auth - this is an indication of a conflicting session (eg. TWS or Web Portal) taking over the credentials. We _logout_, and then _reauthenticate_.
3. else: 🔐 need auth - the session is present, just needs authentication, so we _reauthenticate_.

Irrespectively of which of the three cases take place, we end up with carrying out the post authentication double-checks:

1. Repeatedly check the Status to see if authentication was successful:
   a) Check Status every second, up to `IBEAM_MAX_STATUS_CHECK_RETRIES` times (15 by default)
   b) If all Status checks finish and don't report successful authentication, call _reauthenticate_ once again.
   c) Repeat this whole process up to `IBEAM_MAX_REAUTHENTICATE_RETRIES` times (3 by default)
2. if any of the Status checks reports `not running` or `not session` or `not connected` or `competing` or `not authenticated`:⚠️ something's wrong - the Gateway is having some issues and we aren't going to keep on trying. We'll kill its process. It will be restarted on next maintenance, hoping this will solve the issues.
3. else: ✅ all good - we've verified that the authentication worked! 🥳

## If you want to test this version:

1. Set `IBEAM_AUTHENTICATION_STRATEGY` to `B` in order to test the new strategy
2. Pay attention to how it handles error cases - such as repeated login loops, errors, timeouts, etc.
3. Report any observations, errors and ideas directly in this issue.
4. Accept my sincere thanks for helping us all out 🙏

####  There has been some tidying up of the `gateway_client.py` file:

* moved login/reauth logic into `strategy_handler`
* moved all HTTP/request-related functionality to `http_handler`
* moved all OS process-related functionality to `process_utils`
* moved handling of secrets into `secrets_handler`

#### And minor fixes:

* reworked the `Status` class and handling of Gateway/authentication status 
* added fixes to process starting and killing, ensuring we kill all processes 
* added more verbosity to 'Gateway running and authenticated' by attaching `session_id` and `server_name`
* added support for GET and POST requests according to IBKR docs
* using word 'logging in' when referring to doing a full webpage login, otherwise 'reauthenticate' 
* fixed KeyboardInterrupt behaviour by shutting down the health server

## Roadmap:

* If this new strategy 'B' requires tweaks, we'll work on these as first priority - this is the main goal of the v0.5.0 release.
* ~If there is time, I'd want to look into the `authenticate.py` file and rework that logic there. It has grown from a small function into some nasty rotten spaghetti code and also deserves some love.~
* ~Improve on OOP and testability by unifying all environment variable reading into one place, and pass arguments from then on.~

**Comment by bfoz** [comment]
Here are the logs from my first attempt at using strategy B:

> Attaching to ibeam
ibeam    | WARNING: All illegal access operations will be denied in a future release
ibeam    | 2023-06-29 16:28:35,793|I| Cannot ping Gateway. Retrying for another 19 seconds
ibeam    |  -> mount demo on /demo
ibeam    | Java Version: 11.0.18
ibeam    | ****************************************************
ibeam    | version: 485dc2d762781c4ff3954ac4fb66a9469a1405f7 Mon, 20 Mar 2023 14:39:35 -0400
ibeam    | ****************************************************
ibeam    | This is the Client Portal Gateway
ibeam    | for any issues, please contact api@ibkr.com
ibeam    | and include a copy of your logs
ibeam    | ****************************************************
ibeam    | https://www.interactivebrokers.com/api/doc.html
ibeam    | ****************************************************
ibeam    | Open https://localhost:5000 to login
ibeam    | App demo is available after you login under: https://localhost:5000/demo#/
ibeam    | 2023-06-29 16:28:37,483|I| Gateway connection established
ibeam    | 2023-06-29 16:28:37,816|I| NO SESSION Status(running=True, session=False, connected=False, authenticated=False, competing=False, collision=False, session_id=None, server_name=None, server_version=None, expires=None)
ibeam    | 2023-06-29 16:28:37,816|I| Authentication strategy: "B"
ibeam    | 2023-06-29 16:28:37,816|I| No active sessions, logging in...
ibeam    | 2023-06-29 16:28:37,816|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
ibeam    | 2023-06-29 16:28:47,330|I| Gateway auth webpage loaded
ibeam    | 2023-06-29 16:28:47,330|I| Login attempt number 1
ibeam    | 2023-06-29 16:28:52,689|I| Submitting the form
ibeam    | 2023-06-29 16:29:03,151|I| Webpage displayed "Client login succeeds"
ibeam    | 2023-06-29 16:29:05,151|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7f19761c73d0> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="34f3177e6b18ad0f5eebac5774f1ab7e")>
ibeam    | 2023-06-29 16:29:05,204|I| Logging in succeeded
ibeam    | 2023-06-29 16:29:06,337|I| Repeating status check attempts another 14 times
ibeam    | 2023-06-29 16:29:21,927|I| Max status check retries reached after 15 attempts. Consider increasing the retries by setting IBEAM_MAX_STATUS_CHECK_ATTEMPTS environment variable
ibeam    | 2023-06-29 16:29:21,928|I| NOT CONNECTED Status(running=True, session=True, connected=False, authenticated=False, competing=False, collision=False, session_id='85cab2bd4a8505681028c4664a9dd510', server_name=None, server_version=None, expires=581466)
ibeam    | 2023-06-29 16:29:21,954|I| Repeated reauthentication attempt number 2
ibeam    | 2023-06-29 16:29:23,103|I| Repeating status check attempts another 14 times
ibeam    | 2023-06-29 16:29:38,446|I| Max status check retries reached after 15 attempts. Consider increasing the retries by setting IBEAM_MAX_STATUS_CHECK_ATTEMPTS environment variable
ibeam    | 2023-06-29 16:29:38,446|I| NOT CONNECTED Status(running=True, session=True, connected=False, authenticated=False, competing=False, collision=False, session_id='85cab2bd4a8505681028c4664a9dd510', server_name=None, server_version=None, expires=564917)
ibeam    | 2023-06-29 16:29:38,462|I| Repeated reauthentication attempt number 3
ibeam    | 2023-06-29 16:29:39,638|I| Repeating status check attempts another 14 times
ibeam    | 2023-06-29 16:29:55,207|I| Max status check retries reached after 15 attempts. Consider increasing the retries by setting IBEAM_MAX_STATUS_CHECK_ATTEMPTS environment variable
ibeam    | 2023-06-29 16:29:55,207|I| NOT CONNECTED Status(running=True, session=True, connected=False, authenticated=False, competing=False, collision=False, session_id='85cab2bd4a8505681028c4664a9dd510', server_name=None, server_version=None, expires=548161)
ibeam    | 2023-06-29 16:29:55,221|I| Repeated reauthentication attempt number 4
ibeam    | 2023-06-29 16:29:56,384|I| Repeating status check attempts another 14 times
ibeam    | 2023-06-29 16:30:11,883|I| Max status check retries reached after 15 attempts. Consider increasing the retries by setting IBEAM_MAX_STATUS_CHECK_ATTEMPTS environment variable
ibeam    | 2023-06-29 16:30:11,883|I| NOT CONNECTED Status(running=True, session=True, connected=False, authenticated=False, competing=False, collision=False, session_id='85cab2bd4a8505681028c4664a9dd510', server_name=None, server_version=None, expires=531485)
ibeam    | 2023-06-29 16:30:11,898|I| Repeated reauthentication attempt number 5
ibeam    | 2023-06-29 16:30:13,043|I| Repeating status check attempts another 14 times
ibeam    | 2023-06-29 16:30:28,386|I| Max status check retries reached after 15 attempts. Consider increasing the retries by setting IBEAM_MAX_STATUS_CHECK_ATTEMPTS environment variable
ibeam    | 2023-06-29 16:30:28,386|I| NOT CONNECTED Status(running=True, session=True, connected=False, authenticated=False, competing=False, collision=False, session_id='85cab2bd4a8505681028c4664a9dd510', server_name=None, server_version=None, expires=514991)
ibeam    | 2023-06-29 16:30:28,387|I| Max reauthenticate retries reached after 5 attempts. Consider increasing the retries by setting IBEAM_MAX_REAUTHENTICATE_RETRIES environment variable
ibeam    | 2023-06-29 16:30:28,387|E| Repeatedly reauthenticating failed 5 times. Killing the Gateway and restarting the authentication process.
ibeam    | 2023-06-29 16:30:29,394|I| Starting maintenance with interval 60 seconds

**Comment by bfoz** [comment]
After the maintenance interval:

> ibeam    | 2023-06-29 16:31:32,801|I| Authentication strategy: "B"
ibeam    | 2023-06-29 16:31:32,801|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
ibeam    | 2023-06-29 16:31:39,948|I| Gateway auth webpage loaded
ibeam    | 2023-06-29 16:31:39,948|I| Login attempt number 1
ibeam    | 2023-06-29 16:31:45,301|I| Submitting the form
ibeam    | 2023-06-29 16:32:00,901|E| Timeout reached searching for website elements, but the website seems to be loaded correctly. It is possible the setup is incorrect. 
ibeam    | Website version: 2 
ibeam    | DOM elements searched for: {'USER_NAME_EL': 'username', 'PASSWORD_EL': 'password', 'SUBMIT_EL': 'button.btn.btn-lg.btn-primary', 'ERROR_EL': 'xyz-errormessage', 'SUCCESS_EL_TEXT': 'Client login succeeds', 'IBKEY_PROMO_EL_CLASS': 'ibkey-promo-skip', 'TWO_FA_EL_ID': 'twofactbase', 'TWO_FA_NOTIFICATION_EL': 'login-step-notification', 'TWO_FA_INPUT_EL_ID': 'chlginput', 'TWO_FA_SELECT_EL_ID': 'sf_select'}. 
ibeam    | Exception:
ibeam    |   File "/usr/local/lib/python3.11/threading.py", line 995, in _bootstrap
ibeam    |     self._bootstrap_inner()
ibeam    |   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
ibeam    |     self.run()
ibeam    |   File "/usr/local/lib/python3.11/threading.py", line 975, in run
ibeam    |     self._target(*self._args, **self._kwargs)
ibeam    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
ibeam    |     work_item.run()
ibeam    |   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
ibeam    |     result = self.fn(*self.args, **self.kwargs)
ibeam    |   File "/opt/venv/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
ibeam    |     retval = job.func(*job.args, **job.kwargs)
ibeam    |   File "/srv/ibeam/src/gateway_client.py", line 159, in _maintenance
ibeam    |     success, shutdown, status = self.start_and_authenticate(request_retries=var.REQUEST_RETRIES)
ibeam    |   File "/srv/ibeam/src/gateway_client.py", line 128, in start_and_authenticate
ibeam    |     success, shutdown, status = self.strategy_handler.try_authenticating(request_retries=request_retries)
ibeam    |   File "/srv/ibeam/src/strategy_handler.py", line 84, in try_authenticating
ibeam    |     return self._authentication_strategy_B(status, request_retries)
ibeam    |   File "/srv/ibeam/src/strategy_handler.py", line 139, in _authentication_strategy_B
ibeam    |     return self._log_in(status)
ibeam    |   File "/srv/ibeam/src/strategy_handler.py", line 150, in _log_in
ibeam    |     success, shutdown = self.log_in_function()
ibeam    |   File "/srv/ibeam/src/gateway_client.py", line 106, in _log_in
ibeam    |     return log_in(driver_path=self.driver_path,
ibeam    |   File "/srv/ibeam/src/authenticate.py", line 312, in log_in
ibeam    |     trigger = WebDriverWait(driver, var.OAUTH_TIMEOUT).until(
ibeam    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ibeam    |   File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 95, in until
ibeam    |     raise TimeoutException(message, screen, stacktrace)
ibeam    | 
ibeam    |   <class 'selenium.common.exceptions.TimeoutException'> Message: 
ibeam    | 
ibeam    | 2023-06-29 16:32:00,901|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0x7f1975f99710> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="70896739a2191be3955fe9fb4ae1a233")>
ibeam    | 2023-06-29 16:32:00,951|I| Logging in failed
ibeam    | 2023-06-29 16:32:29,395|I| Maintenance

**Comment by elderanakain** [comment]
@Voyz From my side, it has been running the whole day today, and I didn't observe any issues. I will leave it for the next few days and let you know if something goes wrong.

**Comment by migoohao** [comment]
@Voyz 👏 Strategy B worked well in my server last week, good job! 🥳

- Do not need my app's help now
- No login loop
- recover during maintenance quickly

Let's observe it for more weeks.

**Comment by Voyz** [comment]
@vlpraveen thanks for these logs. I believe the issues you're seeing are caused by IBKR server restarts. The 503 and 500 errors seem to indicate that. If you think these could have a different cause, I'd suggest you create a support ticket with IBKR and speak to them about this.

Regarding the authentication loop, please see: https://github.com/Voyz/ibeam/issues/152#issuecomment-1636123686

**Comment by Voyz** [comment]
Hey friends, I've found time to do a proper revamp and handle the remaining tasks on my roadmap. This involved:

* reworking the authenticate.py. Now it is broken down to step-by-step functions, and hopefully has a much better readability and maintainability. It's functionality has been moved to [login_handler.py](https://github.com/Voyz/ibeam/blob/v0.5.0/ibeam/src/handlers/login_handler.py)
* removing reading environment variables throughout the app. Now all env vars are read in `ibeam_starter.py` and then everything is passed as arguments
* decoupling things from GatewayClient even more. Now we have a bunch of handlers that are responsible for different things
* expanding customisability for different versions of website found. Each env var that specifies the DOM element looked for, requires a `[TYPE]@@[IDENTIFIER]` format, eg.: `CSS_SELECTOR@@.btn.btn-lg.btn-primary` for the primary submit button. I concluded that such system is necessary when I realised that the 2FA forms have a very different layout for different users. Now it can be customised even more.

Breaking changes:

* If you used custom env vars for DOM elements: due to the change in the env var DOM elements processing, you'll need to specify the `[TYPE]@@[IDENTIFIER]`. This will most likely mean you'll need to add `[TYPE]@@` to your existing env vars that specify custom DOM elements if you had any.

I'm pretty happy with the results. Most recent version `voyz/ibeam:0.5.0-rc3` is out, give it a shot when you've got a minute.

**Comment by bfoz** [comment]
Strategy B with 0.5.0-rc3 worked on the first try! 🎉

> ibeam    | 2023-07-16 00:45:31,558|I| Gateway running and authenticated, session id: 96696cdfb672bb6a8617777c6eb6f27e, server name: JifN16024

**Comment by jsilhan** [comment]
I have tried 0.5.0-rc3 and it works perfectly. Thanks! It should be the main strategy. With the default strategy from the stable version I had issues that 70% of the time I have being disconnected and reauthenticated.

**Comment by rm-21** [comment]
This thread helped me a lot! I am running the `0.5.0-rc4`, with auth strategy B and everything runs smoothly. Plus, a quick thank you for creating `ibeam`. Simplified a lot of things for me!

**Comment by Voyz** [comment]
@vlpraveen there's been a separate issue for 503 Service Unavailable: https://github.com/Voyz/ibeam/issues/38. Also, it is being mentioned in other issues too. Seeing that this is only one endpoint, I'd address this with IBKR

**Comment by Voyz** [comment]
Hey guys, `0.5.0` just got released as the `latest` 🥳 I decided to set strategy B as the default, as there seems to be good indication that it performs better than A.

You can see full release notes here: https://github.com/Voyz/ibeam/releases/tag/v0.5.0

Big thanks to you for helping test this version out and reporting back 👏👏👏

**Comment by rbjorklin** [comment]
Hey @Voyz et al. I've been trying to understand how to execute the login flow successfully and stumbled over this issue in search for answers to some of the unexpected behaviour I'm seeing. Would you say the following maps to your understanding & implementation of a successful login flow?
![login-flow](https://github.com/Voyz/ibeam/assets/1704798/81e1aa77-bf6a-4059-9240-59acc80cbd50)

**Comment by demansou** [comment]
@Voyz I had wanted to share that I'm occasionally seeing 503 when POSTing WhatIf orders. Your analysis in the previous issue thread was spot on and a simple log into my paper trading account to raise the compete flag works to get my automation out of its death spiral of failed message processing.

I'm using the latest Docker image in Azure containers. I have seen strategy 'B' in my logs so I assume I've ended up using that.

**Comment by Voyz** [comment]
@rbjorklin thanks for submitting your findings 👏 I'd suggest you start a different issue where we could discuss this

**Comment by Voyz** [comment]
@demansou 

>  Your analysis in the previous issue thread was spot on and a simple log into my paper trading account to raise the compete flag works to get my automation out of its death spiral of failed message processing.


Hold up hold up! Thanks for the credit, but I don't remember mentioning this and this is a great idea. Does doing so get you out of the authentication loop?

Do I understand your solution correctly:

1. Identify being in an authentication loop
2. Log in in a separate instance to create a session conflict and have the `compete` flag on.
3. Original instance sees the conflicting session and tries to solve it, breaking the loop

Could you comment more on this?

**Comment by Voyz** [comment]
@demansou could you please elaborate when you find a minute?

**Comment by demansou** [comment]
Yes sorry I've been on vacation.

1. Ibeam Gateway automates login and session maintenance.
2. I run my trading automation to get market snapshot and POST 'what if' order to get my margin requirements.
3. Order should be placed and some response given from server. But HTTP 503 is received.
4. I rerun automation to double check and get proper responses for each endpoint hit until I place 'what if' order again. HTTP 503
5. I found the information somewhere (thought it was you) to log into IB manually which will raise the compete flag in my session, so I do that.
6. I rerun automation and no 503 issue when placing 'what if' order.

**Comment by Voyz** [comment]
@demansou ahh gotcha you're referring to 503 not the auth loop. I just gave it a shot and indeed it seemed to have helped. I'll try it on the reauth loop too, let's see if it works. Thanks for sharing! 👏👏

**Comment by yezhengli-Mr9** [comment]
```bash
docker run --env IBEAM_ACCOUNT=$IBEAM_ACCOUNT --env IBEAM_PASSWORD=$IBEAM_PASSWORD -p $IBEAM_LISTEN_PORT:5000 voyz/ibeam:0.5.0-rc1
Unable to find image 'voyz/ibeam:0.5.0-rc1' locally
0.5.0-rc1: Pulling from voyz/ibeam
d981f2c20c93: Pull complete
1cf577bcf494: Pull complete
f91900d3cd8d: Pull complete
7e741db19213: Pull complete
7fd77e46ffe0: Pull complete
67eb7977fe7b: Pull complete
325729e59033: Pull complete
08598d96fa03: Pull complete
183ecdbb749d: Pull complete
204cc24a7e92: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:7630b9c571f127de19327af129a06b4e9d069051de7f39362b2451eb007af9c8
Status: Downloaded newer image for voyz/ibeam:0.5.0-rc1
2025-10-26 18:31:41,227|I| ############ Starting IBeam version 0.5.0-rc1 ############
2025-10-26 18:31:41,229|I| Secrets source: env
2025-10-26 18:31:41,230|I| Health server started at port=5001
2025-10-26 18:31:41,230|I| Environment variable configuration:
{'INPUTS_DIR': '/srv/inputs/', 'OUTPUTS_DIR': '/srv/outputs', 'GATEWAY_DIR': '/srv/clientportal.gw', 'CHROME_DRIVER_PATH': '/usr/bin/chromedriver', 'GATEWAY_STARTUP': 20, 'GATEWAY_PROCESS_MATCH': 'ibgroup.web.core.clientportal.gw.GatewayStart', 'MAINTENANCE_INTERVAL': 60, 'SPAWN_NEW_PROCESSES': False, 'LOG_LEVEL': 'INFO', 'LOG_TO_FILE': True, 'LOG_FORMAT': '%(asctime)s|%(levelname)-.1s| %(message)s', 'REQUEST_RETRIES': 2, 'REQUEST_TIMEOUT': 15, 'RESTART_FAILED_SESSIONS': True, 'RESTART_WAIT': 15, 'REAUTHENTICATE_WAIT': 15, 'HEALTH_SERVER_PORT': 5001, 'SECRETS_SOURCE': 'env', 'GATEWAY_BASE_URL': 'https://localhost:5000', 'ROUTE_AUTH': '/sso/Login?forwardTo=22&RL=1&ip2loc=on', 'ROUTE_USER': '/v1/api/one/user', 'ROUTE_VALIDATE': '/v1/portal/sso/validate', 'ROUTE_REAUTHENTICATE': '/v1/portal/iserver/reauthenticate?force=true', 'ROUTE_AUTH_STATUS': '/v1/api/iserver/auth/status', 'ROUTE_TICKLE': '/v1/api/tickle', 'ROUTE_LOGOUT': '/v1/api/logout', 'USER_NAME_EL': None, 'PASSWORD_EL': 'password', 'SUBMIT_EL': 'button.btn.btn-lg.btn-primary', 'ERROR_EL': None, 'SUCCESS_EL_TEXT': 'Client login succeeds', 'OAUTH_TIMEOUT': 15, 'PAGE_LOAD_TIMEOUT': 15, 'ERROR_SCREENSHOTS': False, 'MAX_FAILED_AUTH': 5, 'MIN_PRESUBMIT_BUFFER': 5, 'MAX_PRESUBMIT_BUFFER': 30, 'MAX_IMMEDIATE_ATTEMPTS': 10, 'IBKEY_PROMO_EL_CLASS': 'ibkey-promo-skip', 'AUTHENTICATION_STRATEGY': 'A', 'MAX_STATUS_CHECK_RETRIES': 15, 'MAX_REAUTHENTICATE_RETRIES': 5, 'TWO_FA_EL_ID': 'twofactbase', 'TWO_FA_NOTIFICATION_EL': 'login-step-notification', 'TWO_FA_INPUT_EL_ID': 'chlginput', 'TWO_FA_HANDLER': None, 'STRICT_TWO_FA_CODE': True, 'TWO_FA_SELECT_EL_ID': 'sf_select', 'TWO_FA_SELECT_TARGET': 'IB Key'}
2025-10-26 18:31:41,231|I| Gateway not found, starting new one...
2025-10-26 18:31:41,231|I| Note that the Gateway log below may display "Open https://localhost:5000 to login" - ignore this command.
2025-10-26 18:31:41,231|I| Starting Gateway as Linux process with params: ['bash', 'bin/run.sh', 'root/conf.yaml']
running
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 config file  : root/conf.yaml
2025-10-26 18:31:41,239|I| Gateway started with pids: [14]
2025-10-26 18:31:41,240|I| Gateway running but not serving yet. Consider increasing IBEAM_GATEWAY_STARTUP timeout. Error: <urlopen error [Errno 111] Connection refused>
2025-10-26 18:31:41,240|I| Gateway connection established
2025-10-26 18:31:41,242|I| Gateway running but not serving yet. Consider increasing IBEAM_GATEWAY_STARTUP timeout. Error: <urlopen error [Errno 111] Connection refused>
2025-10-26 18:31:41,242|I| NO SESSION Status(running=True, session=False, connected=False, authenticated=False, competing=False, collision=False, session_id=None, server_name=None, server_version=None, expires=None)
2025-10-26 18:31:41,242|I| Authentication strategy: "A"
2025-10-26 18:31:41,242|I| No active sessions, logging in...
2025-10-26 18:31:41,242|I| Loading auth webpage at https://localhost:5000/sso/Login?forwardTo=22&RL=1&ip2loc=on
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.18
****************************************************
version: 485dc2d762781c4ff3954ac4fb66a9469a1405f7 Mon, 20 Mar 2023 14:39:35 -0400
****************************************************
This is the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo#/
2025-10-26 18:31:49,046|I| Gateway auth webpage loaded
2025-10-26 18:31:49,046|I| Login attempt number 1
2025-10-26 18:31:54,245|I| Submitting the form
2025-10-26 18:32:04,446|I| Webpage displayed "Client login succeeds"
2025-10-26 18:32:06,446|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0xfff9e9bd7810> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="cc3ed71fb139cf98e7a0926d052ced97")>
2025-10-26 18:32:06,505|I| Logging in succeeded
2025-10-26 18:32:09,645|I| Attempt number 2
2025-10-26 18:32:09,809|I| Max request retries reached after 2 attempts. Consider increasing the retries by setting IBEAM_REQUEST_RETRIES environment variable
2025-10-26 18:32:09,809|E| Logging in succeeded but there are still no active sessions
2025-10-26 18:32:09,812|I| Starting maintenance with interval 60 seconds
```

**Comment by Voyz** [comment]
@yezhengli-Mr9 - 5.0.0 is an older version that is no longer supported. Please use the most recent image
