### ISSUE TITLE
SSL error, version number 

### ISSUE THREAD

**Issue by dabrazhe** [Voyz/ibeam#149]
**Describe the bug**
Upon reaching to the localhost:5000 on the host system for the docker, I am getting the following error 
Eg 
curl -X GET "https://localhost:5000/v1/api/one/user" -k
results in 
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**To Reproduce**
1. curl  "https://localhost:5000/v1/api/one/user"  --verbose  
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
2. See error

**Environment**
IBeam version: lastes of 3 of July 2023
DIGEST:sha256:b370977232b157a75247fd5d3b9524e4a36f78c0834c2006242c6e3d828d9801

Docker image or standalone: Image 
OS: Running on Synology DSM 7.0

**Comment by Voyz** [comment]
hey @dabrazhe thanks for describing your issue in detail 👍 

I've never seen that error before, so unfortunately I don't have a solution for you right away. These are some resources I've found on debugging this problem:

https://superuser.com/questions/1754642/ssl-error-wrong-version-number
https://stackoverflow.com/questions/55085550/tls-wrong-version-number-with-openssl-1-1-1
https://stackoverflow.com/questions/50840101/curl-35-error1408f10bssl-routinesssl3-get-recordwrong-version-number
https://community.letsencrypt.org/t/unable-to-establish-ssl-connection-wrong-version-number/155529

Look through these links and see if any of the suggestions there helps in solving the error.

Can you share the command that is used to run the IBeam image?

**Comment by dabrazhe** [comment]
Thank you. 
The image is run via Synology Docker interface, here is a very detailed guide https://linuxhint.com/run-docker-containers-synology-nas/
Below is the json configuration file. 

Just to verify, I need to run the IB GW for authentication with the IB Client API https://interactivebrokers.github.io/cpwebapi/
Is this container image the right one?
``` {
   "CapAdd" : [],
   "CapDrop" : [],
   "cmd" : "/srv/ibeam/run.sh",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enable_service_portal" : null,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "C.UTF-8"
      },
      {
         "key" : "GPG_KEY",
         "value" : "A035C8C19219BA821ECEA86B64E628F8D684696D"
      },
      {
         "key" : "PYTHON_VERSION",
         "value" : "3.11.3"
      },
      {
         "key" : "PYTHON_PIP_VERSION",
         "value" : "22.3.1"
      },
      {
         "key" : "PYTHON_SETUPTOOLS_VERSION",
         "value" : "65.5.1"
      },
      {
         "key" : "PYTHON_GET_PIP_URL",
         "value" : "https://github.com/pypa/get-pip/raw/0d8570dc44796f4369b652222cf176b3db6ac70e/public/get-pip.py"
      },
      {
         "key" : "PYTHON_GET_PIP_SHA256",
         "value" : "96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470ff0d746207"
      },
      {
         "key" : "JAVA_HOME",
         "value" : "/usr/lib/jvm/default-java"
      },
      {
         "key" : "USER_ID",
         "value" : "1000"
      },
      {
         "key" : "GROUP_ID",
         "value" : "1000"
      },
      {
         "key" : "USER_NAME",
         "value" : "basic_user"
      },
      {
         "key" : "GROUP_NAME",
         "value" : "basic_group"
      },
      {
         "key" : "SRC_ROOT",
         "value" : "/srv/ibeam"
      },
      {
         "key" : "OUTPUTS_DIR",
         "value" : "/srv/outputs"
      },
      {
         "key" : "IBEAM_GATEWAY_DIR",
         "value" : "/srv/clientportal.gw"
      },
      {
         "key" : "IBEAM_CHROME_DRIVER_PATH",
         "value" : "/usr/bin/chromedriver"
      },
      {
         "key" : "PYTHONPATH",
         "value" : ":/srv:/srv/ibeam"
      },
      {
         "key" : "IBEAM_ACCOUNT",
         "value" : "myusername"
      },
      {
         "key" : "IBEAM_PASSWORD",
         "value" : "mypassword"
      }
   ],
   "exporting" : false,
   "id" : "0094637c8bcec6cd7ef6299956d425cfe16c8422aa25975faa39b360367d33b6",
   "image" : "voyz/ibeam:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "links" : [],
   "memory_limit" : 0,
   "name" : "voyz-ibeam1",
   "network" : [
      {
         "driver" : "bridge",
         "name" : "bridge"
      }
   ],
   "network_mode" : "bridge",
   "port_bindings" : [
      {
         "container_port" : 5000,
         "host_port" : 550,
         "type" : "tcp"
      },
      {
         "container_port" : 5001,
         "host_port" : 551,
         "type" : "tcp"
      }
   ],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : false,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/ibeam1",
         "mount_point" : "/usr/ibeam",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/ibeam1/env.list",
         "mount_point" : "/env.list",
         "type" : "rw"
      }
   ]
}
```

**Comment by dabrazhe** [comment]
The issue can be closed. The problem went away once I had fixed the synology nas egress, there needs to be a firewall rule to allow traffic to connect to the IB GW.

**Comment by Voyz** [comment]
Hi @dabrazhe glad to hear you've figured out the root cause of the original issue 👏👏

Just to clarify:

> Just to verify, I need to run the IB GW for authentication with the IB Client API https://interactivebrokers.github.io/cpwebapi/
> Is this container image the right one?

Yes, IBeam works with that Gateway, this is the correct image.
