### ISSUE TITLE
Resolving 'Access Denied' Error

### ISSUE THREAD

**Issue by BharathKumar-c** [Voyz/ibeam#154]
I've deployed our IBeam Docker image on my AWS cloud server. However, when I attempt to access the Gateway API endpoints from a different system (with a different IP address), I encounter an error stating "Access Denied".

Could you please provide guidance on how to access these Gateway API endpoints from any location or IP address?

Attached is a screenshot of the error:
![Screenshot 2023-07-27 at 4 02 59 PM](https://github.com/Voyz/ibeam/assets/83769872/9e05b98d-c54a-4ab6-8eb6-659bceba4430)

**Comment by thunderwin** [comment]
so we need to modify docker-compose.yml?
