### ISSUE TITLE
Running iBeam image on standalone mode does not work as expected

### ISSUE THREAD

**Issue by mbehnamj** [Voyz/ibeam#155]
**Describe the bug**
I want to use iBeam's standalone solution so that I can manually enter my IB's credentials into the IB gateway. I noticed to do this all I have to do is to run `python ./ibeam_starter.py --start`(I'm also aware, that with this solution does not maintain the session and I'll need to tickle IB's endpoint separately)

The issue I'm facing is at the time of manually entering my credentials into IB's gateway. Once creds are entered and 2FA code is also entered into the gateway, the URL does redirect to  `/sso/Dispatcher` but the UI does not show `Client login succeeds` or failed, the UI goes back to the initial state(asking for credentials)

![Screenshot 2023-07-31 at 4 10 30 PM](https://github.com/Voyz/ibeam/assets/44380085/dc751bbc-58a7-4b0b-a7d2-cc38940442cb)

![Screenshot 2023-07-31 at 4 10 55 PM](https://github.com/Voyz/ibeam/assets/44380085/9db549c1-3629-4d51-a8ed-428ef87815e4)

![image](https://github.com/Voyz/ibeam/assets/44380085/27601de1-ab42-44e8-81a0-63b3db1fbffc)

In addition, **this issue only exists when** I try to host the docker container on the cloud(AWS or Linode). Everything works perfectly fine on my own machine, Localhost.

**Expected behavior**
Once 2FA entered, the page must show `Client login succeeds`  or failed or something

**Environment**
Latest iBeam image
Other software versions should be as defined within the image
Tried on all different OS except windows

**Additional context**
Soo, I also want to put it out there that I have this same exact issue when I use IB solution out the box(without iBeam). 
I'm just wondering is this is a new measure IB has put in place to prevent hosting their solution on the cloud?!
I understand at this point this might not be iBeam specific issue but I would really appreciate any help on this 🙏

**Comment by mbehnamj** [comment]
console tab before entering credentials:
![Screenshot 2023-07-31 at 5 05 40 PM](https://github.com/Voyz/ibeam/assets/44380085/0f3f1324-1c82-48bb-ad62-7aaf75f664b6)

network tab after entering credentials:
![image](https://github.com/Voyz/ibeam/assets/44380085/770803ba-6b38-4225-bfe9-07da57bfc988)

**Comment by Voyz** [comment]
Hey @mbehnamj thanks for trying out IBeam and describing your issue in detail 👍 

You write:

> I want to use iBeam's standalone solution

But then you mention that you use the 'Latest iBeam image' and the command log you pasted also suggests that. Can you clarify if you're using IBeam as standalone or as a Docker image?

Then, as for the issue itself - I'm not entirely sure what could be causing it. The repeated `Authenticator` requests suggest that something goes wrong with the authentication.

Could you use VPN to attempt from some different countries and see if helps?

> I'm just wondering is this is a new measure IB has put in place to prevent hosting their solution on the cloud?!

Could be. Asking them directly would be the best way to find out.

**Comment by mbehnamj** [comment]
I see the confusion, sorry for that... The image I attached shows the image I created by cloning the iBeam repository, modifying it and creating a new image locally called `ibeam`. 
I also tried it with your official docker image. By saying `latest ibeam image` I meant in terms of software requirements. But in order to get it to work with "manually inputing the credentials in the gateway", I had to modify the image and update `run.sh` to run `python ./ibeam_starter.py --start` 

I also just tried on VPN(pointing to US) but I get the same issue(`/sso/Dispatcher` redirect takes the UI to the login page)

The repeated `Authenticator` requests are all with status code 200 and it's something that I also noticed when running on localhost(with no issues)

@Voyz correct me if I'm wrong, but running your official image(with no changes) on a remote server **successfully** still does not invalidate my issue since iBeam's solution ,even on a remote server, uses local chrome drivers to authenticate, correct?

**Comment by Voyz** [comment]
> I had to modify the image and update run.sh to run python ./ibeam_starter.py --start

Just a side note: you can change the command entrypoint of the docker image that you're running. https://serverfault.com/questions/594281/how-can-i-override-cmd-when-running-a-docker-image This should allow you to accomplish it without changing the image hopefully.

> correct me if I'm wrong, but running your official image(with no changes) on a remote server successfully still does not invalidate my issue since iBeam's solution ,even on a remote server, uses local chrome drivers to authenticate, correct?

IBeam uses chrome driver to start and communicate with a browser. I'm not sure why would that invalidate your issue. 

It seems that this dispatcher redirection is something you'd need to address with IBKR support.

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
