### ISSUE TITLE
Login page not loading when I deploy the IBEAM docker Image but loads in local environment

### ISSUE THREAD

**Issue by Flappizy** [Voyz/ibeam#156]
**Describe the bug**
The issue I am encountering is that when I run this image on my local machine and call the address in my web browser, everything works perfectly, and the Interactive Brokers login page shows up as expected. However, when I host it on a server on a server and call the IP address, an Interactive Brokers page appears without the login form.

I have researched this matter extensively, but it seems like no one else has encountered a similar problem. For context, I am currently connecting using a demo account, and I wonder if that could be contributing to the issue.

I would be immensely grateful if you could offer some advice or guidance on what steps I can take to resolve this matter. Thank you so much for your time and assistance.

**To Reproduce**
1. Pull the Image from the docker hub then run it on local machine everything works fine
2. Host the Image on a server and try to access it on port 5000, a page shows up without the login form
<img width="960" alt="IB_Hosted" src="https://github.com/Voyz/ibeam/assets/75231665/54d085c1-1a6b-4f4b-bf32-4a583485dbed">

**Expected behavior**
The login page to appear
<img width="959" alt="IB_Local" src="https://github.com/Voyz/ibeam/assets/75231665/e246112b-7b69-4338-8f56-d3d20239c0e8">

**Actual behavior**
<img width="960" alt="IB_Hosted" src="https://github.com/Voyz/ibeam/assets/75231665/54d085c1-1a6b-4f4b-bf32-4a583485dbed">

**Environment**
IBeam version: 0.5.0-rc4
Docker image or standalone: Docker Image
OS: Windows 11

**Additional context**
I am currently using a demo account in my env file with the IBEAM Image.

**Comment by Voyz** [comment]
Hey @Flappizy thanks for describing your issue in detail. 

No idea why this could be happening unfortunately. I'd suggest you try to deploy the Gateway on itself on your server and try again. If it repeats, I'd think speaking to IBKR support would be the right way to tackle this, as it doesn't seem like expected behaviour. I don't think you using a demo account would matter here.

https://github.com/Voyz/ibeam/issues/155 has a similar issue of encountering differences between local and remote deployment.

**Comment by Flappizy** [comment]
Alright thank you for your response, I will try to deploy the gateway and see what happens 👍🏾

**Comment by mbehnamj** [comment]
hey @Flappizy. As @Voyz mentioned earlier, I'm facing the same exact issue and I'm still looking for a solution. I've also done quite a bit of research on this(even posted on [Reddit](https://www.reddit.com/r/interactivebrokers/comments/165fufn/cant_host_ib_client_portal_web_api_on_a_remote/) but it "seems" the gateway is not designed for accessing via a remote server...

BUT is this is the case, I'm just not sure how this youtuber was able to do that using Ibeam's image at the time! At the time of video being recorded, Ibeam did not have the 2fa automation solution and the youtuber was able to login to the gateway manually while the portal was hosted on a remote server!

**Comment by moskirathe** [comment]
@mbehnamj @mbehnamj I’ve run into this issue before at a time when I’d deployed a containerised version of the gateway (not ibeam). Increasing the memory on the remote server fixed it (increased it to 4gb)

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
