### ISSUE TITLE
Login Succeeds but fails to maintain authenticated gateway session

### ISSUE THREAD

**Issue by gmara13** [Voyz/ibeam#16]
**Describe the bug**
gateway has been working fine until last night when it gest stuck in a loop of authenticating session.

**To Reproduce**
unknown

**Expected behavior**
the gateway session should remain open and authenticated once login succeeds

**Environment**
IBeam version:
Python version:
OS:

**Additional context**
https://gyazo.com/d5eb1344a1175ad76baae63c40d3e68a

**Comment by Voyz** [comment]
Hey @gmara13 thanks for reporting this issue 👍

Quite frankly there's little we can tell from these logs alone. I've seen this behaviour several times in the past but usually it sorts itself out after a while. Other users have reported this kind of behaviour too, saying this was some issues on IBKR side.

Can I ask you to let IBeam run for some 15 minutes and see if this issue persists? Maybe try at various points during the day?

**Comment by gmara13** [comment]
so this cycle continued for about 1.5 hours then just started working.

**Comment by Voyz** [comment]
Yeah, that also seems similar to what other user's were reporting. It sometimes just goes bonkers unfortunately and we still don't know why. Happy to hear it got back on again for you though

**Comment by gmara13** [comment]
This has been happening more and more frequently. currently been 6 hours of the login cycle. is there somewhere i can see more detailed logs of whats happening?

**Comment by Voyz** [comment]
Hey @gmara13 sorry to hear it is back on again. You can find logs of the gateway in the gateway_folder/logs - these can sometimes provide more information on why things may be breaking. If you notice it happening, I'd try to log in manually using a browser to see if it persists.

**Comment by gmara13** [comment]
had almost a full trading day of this problem come back. im at a loss for what to do

**Comment by Voyz** [comment]
Hey @gmara13 sorry to hear 😟 Once again I'd suggest having a look at `gateway_folder/logs` and see whether something there could be indicating the problem
