### ISSUE TITLE
Access Denied on docker-compose

### ISSUE THREAD

**Issue by thunderwin** [Voyz/ibeam#160]
i m using docker-compose 

here is the config

services:
  ibeam:
    image: voyz/ibeam
    container_name: ibeam
    env_file:
      - env-test.list
    ports:
      - 5000:5000
      - 5001:5001
    network_mode: bridge # Required due to clientportal.gw IP restrictions
    restart: 'no' # Prevents IBEAM_MAX_FAILED_AUTH from being exceeded
    volumes:
      - "./inputs:/srv/inputs"

and I have added my server IP, to the conf.yaml

ips:
  allow:
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - 0.0.0.0
    - 172.17.0.*

and I have checked in the Docker,  conf.yaml mounted well..
 

and I checked the logs says my docker container is running well.. just I can't access it..

**Comment by Voyz** [comment]
Hey @thunderwin thanks for your issue report 👍

Please see https://github.com/Voyz/ibeam/wiki/Troubleshooting#access-denied for fixing Access Denied. Let me know if it helps

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
