### ISSUE TITLE
Access Denied - 403 Error.

### ISSUE THREAD

**Issue by Bharath-itero** [Voyz/ibeam#161]
Hello, There!
I want to express my gratitude for your exceptional dedication and invaluable contributions to IBK gateway authentication.

**Describe the bug**
---------------------
While I run a Docker image, I am encountering an error in the console log.
Simultaneously, when I attempt to open "https://localhost:5000/," I receive an "Access denied" error.
However, the same setup on another EC2 instance is working correctly.

**Environment**
---------------------
IBeam version: latest
Docker image or standalone: Docker image
OS: AWS Ubuntu 

**conf.yaml**
--------------
ip2loc: "US"
proxyRemoteSsl: true
proxyRemoteHost: "https://api.ibkr.com"
listenPort: 5000
listenSsl: true
svcEnvironment: "v1"
sslCert: "vertx.jks"
sslPwd: "mywebapi"
authDelay: 3000
portalBaseURL: ""
serverOptions:
    blockedThreadCheckInterval: 1000000
    eventLoopPoolSize: 20
    workerPoolSize: 20
    maxWorkerExecuteTime: 100
    internalBlockingPoolSize: 20
cors:
    origin.allowed: "*"
    allowCredentials: false
webApps:
    - name: "demo"
      index: "index.html"
ips:
  allow:
    - "*"
  deny:

**Error log**
--------------
<img width="1509" alt="Screenshot 2023-10-19 at 3 19 00 AM" src="https://github.com/Voyz/ibeam/assets/103241982/5762e202-b9f3-4a78-a8ce-fc35d0253861">
<img width="1509" alt="Screenshot 2023-10-19 at 3 19 28 AM" src="https://github.com/Voyz/ibeam/assets/103241982/3407df89-4ff2-4e34-82d1-01bada3f2686">
<img width="1509" alt="Screenshot 2023-10-19 at 3 19 43 AM" src="https://github.com/Voyz/ibeam/assets/103241982/73ed9994-2882-43f5-9e0e-7b6a72517cf9">

**Additional Error Screenshot**
-------------------------------
<img width="1509" alt="Screenshot 2023-10-19 at 3 22 50 AM" src="https://github.com/Voyz/ibeam/assets/103241982/b64b73fd-d751-4d0d-a80a-b3f190ab7499">
<img width="1509" alt="Screenshot 2023-10-19 at 3 24 05 AM" src="https://github.com/Voyz/ibeam/assets/103241982/ffe11625-60b6-43a5-b382-48ef2dc2accb">

Kindly give the solution how to fix this bug..

**Comment by Voyz** [comment]
Hey @Bharath-itero thanks for your issue report and for your kind words 😊👍

Please see https://github.com/Voyz/ibeam/wiki/Troubleshooting#access-denied for fixing Access Denied.
