### ISSUE TITLE
Facing issue while changing the Port Number

### ISSUE THREAD

**Issue by Bharath-itero** [Voyz/ibeam#162]
Hey, There

**Describe the bug**
I'm trying to change from 5000 to 80 port but unable to change it.  
Even in conf.ymal file i have changed to 80 port still it does not change. 
when I run the docker it moves into an authentication loop. I have attached screenshot of this error. 
Looking forward for your suggestion in order to sort this error.

Thanks in advance..

**Environment**
---------------------
IBeam version: latest
Docker image or standalone: Docker image
OS: AWS Ubuntu 

**conf.yaml**
--------------
ip2loc: "US"
proxyRemoteSsl: true
proxyRemoteHost: "https://api.ibkr.com"
listenPort: 80  
listenSsl: true
svcEnvironment: "v1"
sslCert: "vertx.jks"
sslPwd: "mywebapi"
authDelay: 3000
portalBaseURL: ""
serverOptions:
    blockedThreadCheckInterval: 1000000
    eventLoopPoolSize: 20
    workerPoolSize: 20
    maxWorkerExecuteTime: 100
    internalBlockingPoolSize: 20
cors:
    origin.allowed: "*"
    allowCredentials: false
webApps:
    - name: "demo"
      index: "index.html"
ips:
  allow:
    - "*"
  deny:
  
  **Error log**
--------------
<img width="1509" alt="Screenshot 2023-10-19 at 4 02 16 AM" src="https://github.com/Voyz/ibeam/assets/103241982/c0d6a418-c887-4b37-9987-ca2606f58e4d">
<img width="1509" alt="Screenshot 2023-10-19 at 4 02 05 AM" src="https://github.com/Voyz/ibeam/assets/103241982/3bd81c58-d4de-4250-861b-e7240331f542">

**Comment by Voyz** [comment]
Hi @Bharath-itero 

Please see https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#changing-port for changing the port. I'd suggest you avoid using port 80 as I think it is a reserved one: https://www.techopedia.com/definition/15709/port-80

Let me know if that helps 👍
