### ISSUE TITLE
2FA EXTERNAL_REQUEST Issue

### ISSUE THREAD

**Issue by kashyappatel7** [Voyz/ibeam#165]
I updated to the latest version (0.5.0) and now when starting the container, I get the following error message:

```
2023-11-06 15:58:18,622|I| ############ Starting IBeam version 0.5.0 ############
Traceback (most recent call last):
  File "/srv/ibeam/ibeam_starter.py", line 80, in <module>
    two_fa_handler = two_fa_selector.select(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/two_fa_selector.py", line 23, in select
    handler = ExternalRequestTwoFaHandler(outputs_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/two_fa_handlers/external_request_handler.py", line 59, in __init__
    super().__init__(*args, **kwargs)
TypeError: TwoFaHandler.__init__() missing 1 required positional argument: 'outputs_dir'
```

This is the command I'm using to start:
`docker run --env IBEAM_ACCOUNT=******* --env IBEAM_PASSWORD=********** --env IBEAM_TWO_FA_HANDLER=EXTERNAL_REQUEST --env IBEAM_EXTERNAL_REQUEST_URL=https://******.com/sms/code --env IBEAM_EXTERNAL_REQUEST_PARAMS={\"token\":\"***********************************\"} --env IBEAM_LOG_LEVEL=DEBUG --env IBEAM_PAGE_LOAD_TIMEOUT=500 -p 5000:5000 voyz/ibeam`

(I replace sensitive info with ************)

**Comment by Voyz** [comment]
Hey @kashyappatel7 thanks for reporting. I've just pushed a new image `0.5.1` that should fix this bug. Let me know if it helps 👍

**Comment by kashyappatel7** [comment]
Hi @Voyz, that worked!! Thank you so much for the super fast response! @
