### ISSUE TITLE
Healthcheck endpoint for load balancer

### ISSUE THREAD

**Issue by jcity** [Voyz/ibeam#169]
**Describe the feature**
I've been digging around looking for an endpoint to use as a health check for my load balancer.

Does this exist?

**Expected interaction**
A simple endpoint that returns a 200 response indicating the server is up and running

**Additional context**
Background:
I'm deploying this as a Fargate service in AWS and putting the service behind a load balancer. AWS needs a path the load balancer can ping frequently to ensure the service is up and running.

**Comment by jcity** [comment]
Ah looks like this exists just on a different port?

`localhost:5001//livez` looks to be what I'm looking for. Is that the intention of this endpoint?

**Comment by Voyz** [comment]
Hey @jcity I'm glad you've found it, yes, that is the endpoint you should use 👍

There's also `/readyz` for checking if the authentication is successful. `/livez` just indicates that it is up and running.

**Comment by jcity** [comment]
Great, thanks for the response!

I just got everything deployed in an AWS Fargate container. The other thing I had to do to get this to work was add a custom `conf.yaml` file and add an IP (wildcard) to the allow list.

Anything else you can think of that I might run into? Figuring out a 2FA solution is coming soon 🙃

**Comment by Voyz** [comment]
Nice, well done!

2FA indeed may be the next step. Try to see if you can get SMS 2FA from IBKR and then use Google Messages. There's a guide for it in the Wiki: https://github.com/Voyz/ibeam/wiki/Two-Factor-Authentication#google-messages-handler

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
