### ISSUE TITLE
Seeking Support

### ISSUE THREAD

**Issue by kls06541** [Voyz/ibeam#172]
Seeking assistance to configure 'ibeam'—is anyone available for a one-on-one setup session?

**Comment by Voyz** [comment]
@kls06541 Sam, it's audacious that you'd come back to this space and try to request help from other users. 

Open source software is available to all and I cannot prohibit you from using the code I publish. Despite that, your lies, you failing to meet your contractual obligations, you still owing me money for the work you hired me for, and overall your illicit behaviour - are abusive of community standards and work ethics, and for that reason you are not welcome here. I hope one day you reflect on your actions and find way to bring some good into this world instead. I don't intend to be pushing around with you on public forums, therefore until that time please simply leave and focus on other things, but don't come back here.

Anyone else reading this post, please be cautious of working with this individual - Sam Krausz.
