### ISSUE TITLE
CP Web API documentation URL has been deprecated

### ISSUE THREAD

**Issue by bfoz** [Voyz/ibeam#173]
The README currently contains a link to the [Interactive Brokers Client Portal Web API Gateway](https://interactivebrokers.github.io/cpwebapi/) and the page at that address now displays a big scary banner that reads:

> This documentation is now deprecated. Please switch to the [IBKR Campus](https://ibkrcampus.com/ibkr-api-page/ibkr-api-home/) for up-to-date information regarding IBKR's API solutions.

So it looks like the README needs to be updated. Would you like me to submit a PR for this?

**Comment by Voyz** [comment]
Hey! Very well spotted, thanks for mentioning this! I updated the README 👍

**Comment by Voyz** [comment]
That's strange 🤔 Can you try cleaning cache or a different browser? Just checked that link on a couple of browsers and it renders all fine:

![image](https://github.com/Voyz/ibeam/assets/15874847/38763499-f6d0-40c2-aacb-a8c39c4d9961)

That link from the banner (https://ibkrcampus.com/ibkr-api-page/ibkr-api-home/) points at their overall API home, which could mislead some users into TWS API documentation. The API docs we want to point at are the Web API docs - https://ibkrcampus.com/ibkr-api-page/webapi-doc/

**Comment by bfoz** [comment]
The link works properly for me now. I'm not sure what happened. 

That page now has a note at the top that says "Please be aware that IBKR’s unified Web API documentation and reference materials are in beta and subject to change." So maybe something glitched, but it works for me now.

**Comment by Voyz** [comment]
Great to hear 👍 Feel free to close the issue whenever you're ready
