### ISSUE TITLE
Custom TLS certificate failed to start ibeam

### ISSUE THREAD

**Issue by rl3250** [Voyz/ibeam#175]
**Describe the bug**
I've followed the TLS wiki to setup custom certificate, yet it fails to start ibeam due to permission error. I've tried chmod the `cacert.jks` to `u+r` but it's not helping.
```
024-04-08 17:25:35,234|I| ############ Starting IBeam version 0.5.1 ############
2024-04-08 17:25:35,235|I| TLS certificates found and will be used for verification
2024-04-08 17:25:35,236|I| Custom conf.yaml found and will be used by the Gateway
Traceback (most recent call last):
  File "/srv/ibeam/ibeam_starter.py", line 65, in <module>
    http_handler = HttpHandler(
                   ^^^^^^^^^^^^
  File "/srv/ibeam/src/handlers/http_handler.py", line 116, in __init__
    self.build_ssh_context()
  File "/srv/ibeam/src/handlers/http_handler.py", line 123, in build_ssh_context
    self.ssl_context.load_verify_locations(self.inputs_handler.cacert_pem_path)
PermissionError: [Errno 13] Permission denied
```

**Environment**
IBeam version: latest
Docker image or standalone:
Python version (standalone users only):
OS: ubuntu

**Comment by Voyz** [comment]
Hi @rl3250 thanks for trying out IBeam and reporting your issue 👍

I'm not entirely sure how to aid you here without more information. I assume you're running it as a Docker image, which could mean that the Docker container's user 1000 doesn't have permissions to read the file you've mounted. I'd suggest you try various permission modifications to the mounted directory to find a solution.

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
