### ISSUE TITLE
question regarding cloud deployment

### ISSUE THREAD

**Issue by rl3250** [Voyz/ibeam#178]
## Context
It looks like IB Web portal api has the whitelist of localhost access only(also commented in the docker compose file), this makes it hard to be deployed on the cloud and accessed by other services(within the same VPC of course).

It seems like having a reverse proxy is a must in order to productionize it. I wonder if we could have some built-in reverse proxy that simplifies the flow?

**Comment by Voyz** [comment]
Hey @rl3250, are you referring to getting Access Denied error? There is a way to whitelist the IPs, see: https://github.com/Voyz/ibeam/wiki/Troubleshooting#access-denied

If I misunderstood, please clarify 👍
