### ISSUE TITLE
Standalone seems completely broken

### ISSUE THREAD

**Issue by vogelo** [Voyz/ibeam#180]
**Describe the bug**
I tried installing the standalone version (I have my reasons not wanting docker). Results in multiple issues.

After installing ibeam in a fresh conda environment (python 3.12) via pip, the first issue that appears is that all the subfolders of ibeam/src except for two_fa_handlers are missing. 

This causes ibeam_starter.py not to run for various reasons, see below.

**To Reproduce**
Set environment as per readme, installed non-python dependencies.

conda create ibeam
conda activate ibeam
pip install ibeam
python ~/.conda/envs/ibeam/lib/python3.12/site-packages/ibeam/ibeam_starter.py
[error message: ModuleNotFoundError: No module named 'ibeam.src.handlers']
copying missing subfolders (login,utils,handlers) from git repo to ~/.conda/envs/ibeam/lib/python3.12/site-packages/ibeam/src
python ~/.conda/envs/ibeam/lib/python3.12/site-packages/ibeam/ibeam_starter.py
[many incorrect imports from selenium, starts with cannot import name 'TimeoutException' from 'selenium.common']
Changing these errorneous lines one by one to correct imports (e.g. import TimeoutException from selenium.common.exceptions instead of selenium.common) will still not result in a non-functional environment.

Standalone installation seems completely broken?

**Expected behavior**
It should run.

**Environment**
IBeam version: 0.5.1
Docker image or standalone: standalone
Python version (standalone users only): 3.12
OS: arch

**Comment by Voyz** [comment]
hey @vogelo thanks for the detailed issue report and for pointing this out. Indeed very few users use the standalone version, hence it's hard to catch these errors.

I made some fixes to it and released `0.5.3`. Can you give it a shot and let me know if it works for you?

```
pip install ibeam==0.5.3
```

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
