### ISSUE TITLE
Use Ibeam as 3rd party oauth

### ISSUE THREAD

**Issue by elcapitan88** [Voyz/ibeam#181]
Is there a way to make this work where users will put in their own username and password instead of storing it within the code. 
I am trying to make it so my clients do not have to give me their login credentials. 

Thanks for the insight

**Comment by Voyz** [comment]
Hey @elcapitan88 thanks for your question. Just to clarify one thing first:

> Is there a way to make this work where users will put in their own username and password instead of storing it within the code.

The username and password is not stored within the code. It is supplied to a running IBeam instance as environment variables or other types of secrets. See the documentation for more: https://github.com/Voyz/ibeam/wiki/Advanced-Secrets

> I am trying to make it so my clients do not have to give me their login credentials.

This sounds like an implementation detail of your platform that you'd need to figure out on your end. If there is some potential extension to IBeam that would make this easier for you, please feel free to elaborate.

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
