### ISSUE TITLE
IBKR 2FA Requirement

### ISSUE THREAD

**Issue by kaykhan** [Voyz/ibeam#191]
HI friends,

It would appear a lot of the hastle comes from re-authentication with the 2FA process. Does anyone know if its possible to open up a IBKR account without using 2FA?

**Comment by Voyz** [comment]
Hey @kaykhan According to IBKR this is not possible. See: https://ibkrcampus.com/ibkr-api-page/cpapi-v1/#auth-faq


>Q: Is it possible to authenticate a live brokerage session without the use of a Two Factor Authentication (2FA) device?
> A: The login process to the Client Portal API Gateway is the same as to Client Portal. As the Client Portal has access to sensitive information and banking functionalities, two-factor authentication is mandatory for login.

**Comment by kaykhan** [comment]
> Hey @kaykhan According to IBKR this is not possible. See: https://ibkrcampus.com/ibkr-api-page/cpapi-v1/#auth-faq
> 
> > Q: Is it possible to authenticate a live brokerage session without the use of a Two Factor Authentication (2FA) device?
> > A: The login process to the Client Portal API Gateway is the same as to Client Portal. As the Client Portal has access to sensitive information and banking functionalities, two-factor authentication is mandatory for login.

Okay thats unfortunate. Thanks for getting back to me.

Just a follow up question. The reason we are using CPAPI API (With the AUTH limitation) and not the regular WEB API (I believe without the auth limitatino) is because you need to have an "Institutional Account".

Has anyone gone through the process of creating any institutional account, does anyone know what is required?

![image](https://github.com/Voyz/ibeam/assets/5202527/17d97d29-7f84-4ab9-863a-4d778d54f897)

**Comment by HaSiMiPa** [comment]
> Has anyone gone through the process of creating any institutional account, does anyone know what is required?

Hi @kaykhan I have both, private ans institutional accounts. Well, you need to **have** an institution and provide way more documents of proof to IB, compared to a private person. 
But also with this account, 2FA is required. And.. i wonder why somebody would not want to have it. It is a security layer that protects you.
I have multipple iBeam instances running in a docker 24/5 since weeks, I never get any re-authentication requests. (only happens to me on the weekend when IB do maintenance, but on the weekend I usually pause iBeam).

**Comment by kaykhan** [comment]
> > Has anyone gone through the process of creating any institutional account, does anyone know what is required?
> 
> Hi @kaykhan I have both, private ans institutional accounts. Well, you need to **have** an institution and provide way more documents of proof to IB, compared to a private person. But also with this account, 2FA is required. And.. i wonder why somebody would not want to have it. It is a security layer that protects you. I have multipple iBeam instances running in a docker 24/5 since weeks, I never get any re-authentication requests. (only happens to me on the weekend when IB do maintenance, but on the weekend I usually pause iBeam).

Hi @HaSiMiPa  My problem is not with 2FA in general, its the pain points that come with having to reauthenticate and relying on a 3rd party tool like IBeam having to use a headleses browser to get this working reliably. Again my gripe is with IBKR and appreciate that someone has made this effort. Before i go into this approach i just want to make sure ive exhausted my other options. 

1. I appreciate you mentioning that you have IBeam running in a docker 24/5 and you never get reauthentication requests. (Is that with your institutional account or your individual private account) ? 

- Additionally what does your setup look like, are you using twillio with a seperate phone number?
- Is your docker setup by any chance publicly available? :)

2. Can you go into a bit more detail what is required for an institutional account, is this just a business (LLC) you need have registered? Or is there something special about it?

**Comment by HaSiMiPa** [comment]
> 1. I appreciate you mentioning that you have IBeam running in a docker 24/5 and you never get reauthentication requests. (Is that with your institutional account or your individual private account) ?

Both, there is no difference. 

> * Additionally what does your setup look like, are you using twillio with a seperate phone number?

No. I use default IB 2FA app on my cell.

> * Is your docker setup by any chance publicly available? :)

iBeam supports Docker out of the box. Go into your Docker app and search iBeam.
> 
> 2. Can you go into a bit more detail what is required for an institutional account, is this just a business (LLC) you need have registered? Or is there something special about it?

In my case it is a _LLC-like_ business. You should talk to IB directly to get more information on different types of instituations and their requirements.

**Comment by kaykhan** [comment]
I understand i assumed you had this deployed on a linux machine, but it appears you have this running on your local machine which does make it easier to handle the 2fa process.
