### ISSUE TITLE
504 error on socket connection

### ISSUE THREAD

**Issue by redfoo22** [Voyz/ibeam#22]
Everything works for web api.... but I need to connect my python bot to the IB gateway via activeX and sockets. If I run IB gateway on my mac it works on port 4001 but when I run the docker Ibeam IB Gateway it will not connect,504 error, on either port 5000 or 4001. please advise... thanks -foo

**Comment by Voyz** [comment]
Hey @redfoo22 thanks for your issue report 👋 

Could I ask you to provide more details by filling out the issue template so we could understand your setup better? Do you manually change the port to 4001?

**Comment by redfoo22** [comment]
Describe the bug A clear and concise description of what the bug is.

To Reproduce Steps to reproduce the behavior:

Go to 'docker run --env-file env.list -p 5000:5000 voyz/ibeam'
    This will launch my IB app on my phone and I authenticate with FACE ID.
    Then get this in terminal
        2021-06-15 20:15:59,615|I| Gateway running and authenticated
        2021-06-15 20:16:59,637|I| Gateway running and authenticated
        2021-06-15 20:17:59,429|I| Gateway running and authenticated
    
    Everything seems fine at this point.
    I run my trading bot script that I normally use to connect to IB Gateway 978...
    I normally connect on port 4001 but since I specify ports 5000:5000 
    I switch the code on my trading bot too:
       self.ib.connect("127.0.0.1", 5000,39) #ibeam 
    when I run the script i get this error
        Disconnected; resetting connection
    so on my IB gateway that i run on my MAC:
        Read-Only API is unchecked
        Port number is 4001
    On gitHub I checked the ibeam ib gateway code and it says' port 4001
        so I ran the script with port 4001:5000 and 5000:4001 and 4001:4001 and it still din't work.
    I'm new to docker so editing the ibeam ib gate way code before runing a newly built docker image is something I need to learn how to do.
    
    





    
Click on 'N/A'
Scroll down to 'N/A

See error
Expected behavior A clear and concise description of what you expected to happen.

Environment IBeam version:  latest from github.  on my computer Python version: Python 3.7.4 OS: MacOs big Sur 11.2.3

Additional context Add any other context about the problem here.


Suggest a Fix If you can't fix the bug yourself, perhaps you can point to what might be causing the problem (line of code or commit).
    I have a feeling that on the ibeam docker image Read-Only API needs explictly marked as false or somethhing.
    Maybe if there were flags to configure IB_gate_way ports and read onlys and the parms nessasry to connect via websockets...
    and only allow connections from localhost should be able to be configured as well

I have a lot of time for this so I can help thanks -foo

**Comment by Voyz** [comment]
Thanks for including all the additional details @redfoo22 👍

Can I ask you, what is the `self.ib` on this line?

```python
self.ib.connect("127.0.0.1", 5000,39) #ibeam 
```

You say:

> I run my trading bot script that I normally use to connect to IB Gateway 978 

IBeam doesn't work with the TWS Gateway 978, but with the CP Web API Gateway - these are different services. Running both TWS Gateway and IBeam may cause problems.

Additionally, I'd verify if port 5000 is not occupied by any other program.

**Comment by Voyz** [comment]
@redfoo22 closing this down due to inactivity. Let me know if you would like to reopen this issue and restart the conversation. Thanks for reporting! 👋
