### ISSUE TITLE
docker with custom port

### ISSUE THREAD

**Issue by yezhengli-Mr9** [Voyz/ibeam#230]
**Describe the feature**
A clear and concise description of what feature you'd like to suggest.
```bash
 sudo docker run --env IBEAM_ACCOUNT=$IBEAM_ACCOUNT --env IBEAM_PASSWORD=$IBEAM_PASSWORD -p 6000:5000 voyz/ibeam
```
seems docker succeeded login but still cannot use 6000.
**Expected interaction**
How would users interact with the feature. Include code if possible.

**Possible implications**
Describe which parts of the existing system could this feature affect and in what way.

**Additional context**
Add any other context about the feature here.

**Comment by yezhengli-Mr9** [comment]
6000 -> 6005 seems then work.  Thanks very much for the support.

**Comment by Voyz** [comment]
Hey @yezhengli-Mr9 happy to hear you've figured it out on your own 🙌
