### ISSUE TITLE
Documentation Error? san.cnf sample file missing

### ISSUE THREAD

**Issue by MaanasPeri23** [Voyz/ibeam#27]
**Describe the bug**

May need to follow up on this error that I'm trying to debug, but under the 'TLS Certificates and HTTPS' and 'Creating a PEM File', step #2, you said that there would be a sample san.cnf file to use as reference in the documentation (as attached below)
<img width="947" alt="Screen Shot 2021-08-02 at 9 04 53 PM" src="https://user-images.githubusercontent.com/43656322/127941711-c1907400-c390-4774-bdf3-0fb7ae1f65b0.png">

**Comment by Voyz** [comment]
Hey @MaanasPeri23 well spotted 👏 I've just fixed the documentation.

You can find this file in the support folder at:

https://github.com/Voyz/ibeam/blob/master/support/san.cnf

Thanks for catching this 😊
