### ISSUE TITLE
Authentication Process Failed 

### ISSUE THREAD

**Issue by mattspinach** [Voyz/ibeam#29]
*Describe the bug**

When running the command $ docker run --env-file env.list -p 5000:5000 voyz/ibeam:0.3.0-rc7 , I encounter the following error/s: 

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2021-08-31 10:36:19,964|I| ############ Starting IBeam version 0.3.0-rc7 ############
2021-08-31 10:36:19,992|I| Gateway not found, starting new one...
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 verticle     : 
 config file  : root/conf.yaml
2021-08-31 10:36:21,005|I| Gateway started with pid: 24
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.9.1
****************************************************
version: b5beb780761419a2f516040b40c47ec99d5f077e Wed, 24 Feb 2021 17:22:21 -0500
****************************************************
This is a Beta release of the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo/
2021-08-31 10:36:30,596|I| No active sessions, logging in...
2021-08-31 10:36:33,171|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 150, in authenticate_gateway
    driver = start_driver(base_url, driver_path)
  File "/srv/ibeam/src/authenticate.py", line 270, in start_driver
    raise e
  File "/srv/ibeam/src/authenticate.py", line 258, in start_driver
    driver = new_chrome_driver(driver_path)
  File "/srv/ibeam/src/authenticate.py", line 47, in new_chrome_driver
    driver = webdriver.Chrome(driver_path, options=options)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=89.0.4389.82)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 238, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2021-08-31 10:36:33,216|I| Authentication process failed
2021-08-31 10:36:34,916|I| ############ Starting IBeam version 0.3.0-rc7 ############
2021-08-31 10:36:35,021|I| Starting maintenance with interval 60 seconds
2021-08-31 10:37:36,108|I| No active sessions, logging in...
2021-08-31 10:37:38,676|E| Error encountered during authentication

**To Reproduce**
1. Open docker 
2. Run a container (using command line in VSCode)
3. Starting up docker image using env.list file
4. Authenticaton process failed 

**Expected behavior**
The above steps 1-3 should lead to "Gateway running and authenticated" 

**Environment**
IBeam version: 0.3.0-rc7 
Docker image or standalone: image
Python version: 3.9.6 
OS: Mac OS 11.4 (Apple M1) 

**Additional context**
For reference, if I go to https://localhost:5000 and enter my credentials manually, I'm able to establish a connection successfully (only with my live account details) But, if I log in with my paper credentials, although https://localhost:5000 shows client login successful, I cannot see a successful authentication from my command line. Do you have any idea how I can connect my paper trading account specifically? (as I'd like to test my strategy on my paper account first). 

**Suggest a Fix**
Not sure if it's anything to do with (bool, bool) (line 129 authenticate.py) and (bool, bool, bool) (line 48 http_handler.py)   

I'd really appreciate your assistance as I'm quite stuck! 

PS: love your work

**Comment by Voyz** [comment]
Hi @mattspinach welcome to IBeam and thanks for writing this issue report 👋

Let me address a few things first:

1. Are you running it on a M1, ie. ARM processor? Others have attempted to do so and found it impossible. I've tried to compile an ARM image but also wasn't successful in doing so. You can read more about it here: https://github.com/Voyz/ibeam/issues/17

1. The current latest version is `0.3.0`. Is there any reason why you're using `0.3.0-rc7`?
1. Has this issue happened several times? Can you let IBeam run for 10 minutes and observe if this issue continues to repeat, or whether some other issues apear later?

**Comment by mattspinach** [comment]
Hi @Voyz 

Thank you so much for your reply. I'm totally new to coding (I'm more of a trader with a finance background who's stepped foot into the programming space for the first time) and I'm attempting to build a bot that will trade for me, so your assistance is really, really appreciated. 

1. Yes, I am running it on the M1. That's quite unfortunate that the M1 chip is the cause of my problems, but I wanted to ask, if I was to run this on an AWS EC2 instance (say Linux), then I wouldn't have this issue, is that safe to say? I'm planning to deploy my code to the cloud anyway as I intend to have it running 24/7 (as that would take away the need for me to keep my computer running all the time or setting up a Raspberry Pi and worrying about internet/power outages), so if that's the case, then maybe an EC2 instance is the way to go? 
2. I decided to run it on 0.3.0-rc7 to see if that would make a difference which it didn't. 
3. This issue happens every time I run $ docker run --env-file env.list -p 5000:5000 voyz/ibeam and keeps looping the failed authentication (even after letting it run for 20 minutes or more) 

Once again, thank you so so much for your help. Look forward to hearing from you.

**Comment by mattspinach** [comment]
@Voyz I've been able to resolve the issue with the help of #31 

Thanks for your help !

**Comment by Voyz** [comment]
Fantastic @mattspinach I'm glad to hear that 👍😊 Closing the issue in this case, feel free to reopen if these problems return

**Comment by mattspinach** [comment]
Hi @Voyz I wanted to ask whether you've been running IBeam consistently for some time now because I noticed that IBKR's server was being quite buggy when I was testing it a couple weeks ago. I had Ibeam running and keeping me authenticated and it worked quite well most of the time but I believe it was IBKR's server that just wasn't reliable.

**Comment by Voyz** [comment]
To some extent I use it consistently since around February 2021, however I also encounter the issues you're describing @mattspinach. IBKR server indeed is not reliable, so depending on your case you may want to look for a more robust solution. I wish it was otherwise, and I'm hoping sooner or later IBRK will fix these issues, in which case trading using the Client Portal Web API (and through it using IBeam) will become a lot more reasonable of a solution 🤷‍♂️
