### ISSUE TITLE
Error when adding the custom conf.yaml file

### ISSUE THREAD

**Issue by Wenuka** [Voyz/ibeam#30]
Hi,

I have successfully ran the gateway using the docker image, However, when I tried to add my own certificate following the steps mentioned in[ the wiki](https://github.com/Voyz/ibeam/wiki/TLS-Certificates-and-HTTPS), I am getting the following error message,

```
2021-08-31 11:21:39,861|I| ############ Starting IBeam version 0.3.0 ############
2021-08-31 11:21:39,868|I| Gateway not found, starting new one...
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 verticle     : 
Cannot create property=ccp for JavaBean=ibgroup.web.core.clientportal.gw.Config@7f010382
 in 'reader', line 1, column 1:
    ip2loc: "US"
    ^
Unable to find property 'ccp' on class: ibgroup.web.core.clientportal.gw.Config
 in 'reader', line 6, column 6:
    ccp: false
         ^

2021-08-31 11:21:40,881|E| Cannot communicate with the Gateway. Consider increasing IBEAM_GATEWAY_STARTUP
2021-08-31 11:21:41,567|I| ############ Starting IBeam version 0.3.0 ############
2021-08-31 11:21:41,628|I| Starting maintenance with interval 60 seconds
```

When I remove the cpp from the conf.yaml, this error no longer coming, but it gives the following error at a later stage,

```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'localhost'. (_ssl.c:1076)
```

Thanks in advance for your help.

**Comment by Wenuka** [comment]
To update, I just found the problem is arising when I add the conf.yaml (exactly same conf.yaml file provided).

**Comment by Wenuka** [comment]
Hi,

As I have already mentioned, removing ```cpp: false`` from conf.yaml solved the problem. 

Regarding the SSL Certification issue, adding localhost and sample.local to the san.cnf when generating the certificate solved the issue.

Sorry for the trouble.

**Comment by Voyz** [comment]
Hi @Wenuka thanks for your issue report and for using IBeam 😊

Indeed, there was a mistake in the `conf.yaml` file listed on the Wiki - my apologies for the trouble this caused. I'm glad to see you've figured out how to fix it. I've modified the Wiki now and it no longer includes `cpp:false`. 

Also happy to see that you managed to get the SSL working for you. Indeed, modifying the SAN is the correct way to do it. Well done 👏

**Comment by Wenuka** [comment]
Thank you very much @Voyz for your kind reply and also for the wonderful project. :1st_place_medal:

**Comment by Voyz** [comment]
Thanks @Wenuka ! Hope you enjoy using it 😊
