### ISSUE TITLE
Locking out because of invalid username / password error

### ISSUE THREAD

**Issue by popiol** [Voyz/ibeam#32]
Hi, just a small suggestion.

The script constantly retries to log in, even in the case of invalid username / password combination, which leads to locking the account. That's a bit unfortunate ;) especially that the error may appear even if the username and password are actually correct.

I would expect that the script stops running in the case of that error, or at least waits longer before the next attempt. 

Thanks

**Comment by Voyz** [comment]
Hi @popiol thanks for your suggestion 👍

In fact the mechanism you describe is already present, you can read more about it here: https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#max-failed-authentications

Would you expect a different behaviour? Could you describe your exact issue in more details? Use the Issues template if possible.

Thanks!

**Comment by popiol** [comment]
Ok, it doesn't seem to work then... I will open a new issue with bug template

**Comment by Voyz** [comment]
closing this issue and carrying on in #33
