### ISSUE TITLE
How to prevent `No active sessions, logging in...` issue?

### ISSUE THREAD

**Issue by alex1999Tra** [Voyz/ibeam#41]
**Describe the bug**
The Gateway was running and authenticated for a couple of hours. Then it returned `No active sessions, logging in...`. I do have a scheduled job to call `GET /v1/api/iserver/accounts` every 10 min (Suppose this would keep the session active, right?). 

Wondering how to prevent this `No active sessions` issue? It is just so annoying to approve the IB on my phone every time `No active sessions, logging in...` happens.

**Comment by Voyz** [comment]
This seems to be a reoccurring issue that is not dependant on IBeam but on IBKR and their servers dropping authentication within the currently open session. Are you sure you aren't opening the mobile app or the client portal in the meantime? This may cause the drop in the authentication.

> Suppose this would keep the session active, right?

I don't know if it indeed will, I've noticed these statements to not be exactly true.

**Comment by Voyz** [comment]
Hey @alex1999Tra I'm going to close this issue due to lack of activity. Feel free to reopen it if you'd like to continue the conversation 👍
