### ISSUE TITLE
IB Updates

### ISSUE THREAD

**Issue by itxp2008** [Voyz/ibeam#42]
Talking to IB Support:

I've asked about keep alive(session, brokerage session, ping, etc) I'll paste some answers here, hope it helps. My case the session lasts about 3h(what I've seen in my previous run).
"Yes, we are aware of this behavior. We have increased the session to 24 hours some time ago, but currently, it lasts it previous time limit of max 3 hours. We are currently in the process of fixing this issue"

The reauthenticate isn't working as designed, you'll have to re-login:
"Yes, because it required you to reauthorize"

I've asked about how to manage or how I can do reauthentication without human intervention(basically how they've designed it to be used):
"No, via CP Gateway it is not possible. Only OAuth grants automatic authnetication and authorization. However, once we fix 3/24 hours session issue, we will be implementing 7 days session timeframe"

Asked about how is the progress on it, if currently is in development or should I expect it months from now:
"Yes, it is on the road map. It all depends on the difficulty of implementation. As the current limit of 3/24 hours is bound to CLient Portal itself."

Hope it helps

**Comment by tredondo** [comment]
Have you received any updates? People in #150 would be very interested (@automiamo, @lappchan)

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
