### ISSUE TITLE
2FA while running docker

### ISSUE THREAD

**Issue by JohnLiz** [Voyz/ibeam#45]
After using the command run --env-file env.list -p 5000:5000 voyz/ibeam, the process attempts to initiate a 2fa but immediately fails and continues to fail each 1-2 seconds. The "Your request authenticate code" process does get initiated, with the code. But shouldn't their be a way to take that auth code and pass it through? 

I'm also afraid that when starting up the docker and the 2FA failing and attempting to try again within 1 second will lock my account. Isn't that something i should be concerned with?

**Comment by Voyz** [comment]
Hey @JohnLiz thanks for submitting the issue report 👍

> The "Your request authenticate code" process does get initiated, with the code. But shouldn't their be a way to take that auth code and pass it through?

Did you try looking at https://github.com/Voyz/ibeam/wiki/Two-Factor-Authentication for 2FA handling? Are you talking about something that is not currently available using the methods described there?

> I'm also afraid that when starting up the docker and the 2FA failing and attempting to try again within 1 second will lock my account. Isn't that something i should be concerned with?

We haven't had reports of failed 2FA attempts locking up the account, but let us know if that indeed is the case and we can do something about it in future versions.

Thanks! 😊 Voy

**Comment by JohnLiz** [comment]
Thanks for the quick response @Voyz 

So i did look at https://github.com/Voyz/ibeam/wiki/Two-Factor-Authentication but it didn't seem to straight forward. If i want to use a personal number and receive the 2FA code through that number to my personal phone (iPhone/Android) would I just use the EXTERNAL_REQUEST?

My thought process is to some how have the code sent to my phone by TD and i take that code and some how send it back through iBeam (iBeam is somehow waiting for that code for x amount of time, and will timeout after x amount of time of waiting) and from there its authenticated or denied due to bad code.

**Comment by Voyz** [comment]
Thanks for expanding on your issue @JohnLiz 👍

> My thought process is to some how have the code sent to my phone by TD and i take that code and some how send it back through iBeam (iBeam is somehow waiting for that code for x amount of time, and will timeout after x amount of time of waiting) and from there its authenticated or denied due to bad code.

Unfortunately this is not currently possible out of the box, IBeam doesn't have a way to have a code sent to it.

However, IBeam can be configured to send a 2FA request to any URL you ask it to, therefore if you'd like you could set up a server that you could pass the code from your phone manually, which would be pinged by IBeam using `EXTERNAL_REQUEST`.

Alternatively, you could set up a [custom 2FA handler](https://github.com/Voyz/ibeam/wiki/Two-Factor-Authentication#custom-2fa-handler) that indeed would start a server and listen to requests, which would then allow you to create a way to send the code directly to it.

Also, if I understand correctly some IBKR customers only need to approve the log in on their phone, rather than having to pass a 2FA code - you may want to check if that's available in your region.

Hope it helps 👍

**Comment by JohnLiz** [comment]
Thanks so yea I was aware of IBEAM_TWO_FA_HANDLER, but wasn't sure how to fully leverage it because I had tested it and got some issues in the past. 

|W| No 2FA code returned. Aborting authentication.
|I| Credentials correct, but Gateway requires two-factor authentication.
|I| Attempting to acquire 2FA code from: ExternalRequestTwoFaHandler(method=POST, url=https://test.domain.com/api/get, timeout=300, params=None, headers=None)

I'm guessing the information below for my env.list is correct?

IBEAM_TWO_FA_HANDLER=**EXTERNAL_REQUEST**
IBEAM_EXTERNAL_REQUEST_METHOD=**POST**
IBEAM_EXTERNAL_REQUEST_URL=**https://test.domain.com/api/get**
IBEAM_EXTERNAL_REQUEST_TIMEOUT=**300**
#IBEAM_EXTERNAL_REQUEST_PARAMS=
#IBEAM_EXTERNAL_REQUEST_DATA=
#IBEAM_EXTERNAL_REQUEST_HEADERS=

So just to get a confirmation no way to have iBeam wait a couple of second for a code right after |I| Attempting to acquire 2FA code from: ExternalRequestTwoFaHandler(method=POST, url=https://test.domain.com/api/get, timeout=300, params=None, headers=None) ?

**Comment by JohnLiz** [comment]
Close

**Comment by Voyz** [comment]
Yes @JohnLiz that looks like a correct configuration. 

> So just to get a confirmation no way to have iBeam wait a couple of second for a code

Oh we can surely add it in if you'd find it useful, but how would you imagine this should work? Wait for the code and then what?
