### ISSUE TITLE
Allow customisation of log format

### ISSUE THREAD

**Issue by JackD111** [Voyz/ibeam#46]
I've got a small suggestion. Right now it's not possible to change the log format string at https://github.com/Voyz/ibeam/blob/master/ibeam/src/logs.py#L16

`formatter = logging.Formatter('%(asctime)s|%(levelname)-.1s| %(message)s')`

It would be great, if the format string could be customized with environment variables. I've started using the docker gelf logger to send my docker logs to my Seq logging instnace. It seems the gelf parser somehow interprets specific characters to determine the log level of the messages. Essentially, all messages from the ibeam get recognized as error log level. Essentialy, I'd like to remove the time and level name since I belive that that is the reason the messages get parsed as errors since other log messages from the gateteway don't cause that problem. Since I haven't figured out how to adjust the gelf parser I'd think this would be the fastest fix for this

**Comment by Voyz** [comment]
Good suggestion JackD111 - just pushed out `voyz/ibeam:0.4.0-rc4` containing IBEAM_LOG_FORMAT environment variable that you can set to whatever logging format you desire.

**Comment by JackD111** [comment]
Thank you for the quick action. The new environment variable works perfectly. Interestingly enough it still doesn't have the expected log level iny my Seq instance. Somehow the ibeam messages are all still recognized as error level while some most of the gateway messages are info level, I'll have to dig deeper into this...
![image](https://user-images.githubusercontent.com/3951120/146775617-a0813385-902f-466c-b4c7-047c5956b231.png)
