### ISSUE TITLE
Can anyone provide me with a sample Request Body for OPT?

### ISSUE THREAD

**Issue by JohnLiz** [Voyz/ibeam#49]
Hi, I may have a bug that I noticed. But before that I would like to ensure its not on my end.

Can anyone post a JSON Request Body for Options that has proved to be successful with a response? It can be something like buy @ market, etc.

Thanks

**Comment by Voyz** [comment]
Hey @JohnLiz thanks for posting this issue 👍 Note that in general the responses you receive are coming directly from the Gateway not from IBeam, therefore if you'd see an issue with the response it's most likely an issue that you'd want to address with IBKR directly through their technical support or try posting at https://www.reddit.com/r/interactivebrokers/. Could you clarify to which exact endpoint and what parameters you'd like to see a response to?

**Comment by JohnLiz** [comment]
https://localhost:5000/**v1/api/iserver/account/{accountId}/orders** This is the endpoint i'm trying to hit but I'm not sure if the JSON payload format is correct. I was hoping for an example application/json order request info that's needed in order to get a 200 response. Thanks
