### ISSUE TITLE
Being kicked out of IBKR server daily. 

### ISSUE THREAD

**Issue by pcp0129** [Voyz/ibeam#53]
Hi, I am not too skilled in programming but I will try to explain my issue. 
I've been running running voyz/ibeam:0.4.0-rc2 for about a month now, and all has been good. The server would have a connection issue at around 11:03 PM, 12:15 AM, and 12:30 AM consistently for about a month, where the docker printout says due to "Gateway session found but not authenticated, authenticating..." or "Gateway session active but not authenticated" or "Unrecognised HTTPError" and then it resolves itself, but recently (a few days) it has been kicking me out at roughly US equities open time (8:35 AM). From the docker printout, it says due to an .. "Gateway session found but not authenticated, authenticating..." followed by a "Error displayed by the login webpage: Invalid username password combination".
Am I the only one having this problem? My intention is to have the connection and authentication working continuously. Thank you

**Comment by stopdesign** [comment]
You are not alone. After a few months of working with various IBKR Gateways I've lost hope of having a reliable connection.

**Comment by pcp0129** [comment]
> You are not alone. After a few months of working with various IBKR Gateways I've lost hope of having a reliable connection.

It is reassuring to hear that I am not the only one having this connection issue, but don't lose hope. I have great admiration for Voyz and this program. Its just weird that this issue of disconnecting at US equities market open has begun. I will get in contact with IBKR support and see if there any any known reason or roadmap towards improving this.

**Comment by Voyz** [comment]
I'm sorry to hear this affects you @pcp0129 - and thanks for the kind words of support 👍 Contacting IBKR in order to pressure them to fix these connectivity issues seems to be the the right way to go.

This indeed is a problem that affects many users, if you'd like to read more please see:

https://github.com/Voyz/ibeam/issues/19
https://github.com/Voyz/ibeam/issues/7
