### ISSUE TITLE
Gets into rapid 2FA handler failure loop - 0.4.0-rc5

### ISSUE THREAD

**Issue by Qarj** [Voyz/ibeam#54]
**Describe the bug**
After starting the docker container version `0.4.0-rc5` it gets into a fairly rapid 2FA failure loop. The first time it did this I got around 5 SMS messages with my 2FA code, in a panic I shut down the computer to stop it blocking my account.

Here is a log showing the output which I aborted after learning how to do a docker kill

```
2022-01-25 22:26:56,380|I| ############ Starting IBeam version 0.4.0-rc5 ############
2022-01-25 22:26:56,382|I| Gateway not found, starting new one...
2022-01-25 22:26:56,382|I| Note that the Gateway log below may display "Open https://localhost:5000 to login" - ignore this command.
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 verticle     : 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.12
****************************************************
version: ed4af2592e9dd4a784d5403843bd18292fd441ea Fri, 9 Nov 2018 13:23:18 -0500
****************************************************
This is a Beta release of the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo/
2022-01-25 22:26:57,386|I| Gateway started with pid: 12
2022-01-25 22:26:58,132|I| No active sessions, logging in...
2022-01-25 22:27:07,373|I| Credentials correct, but Gateway requires two-factor authentication.
2022-01-25 22:27:07,373|I| No 2FA handler found. You may define your own 2FA handler or use built-in handlers. See documentation for more.
2022-01-25 22:27:07,373|W| No 2FA code returned. Aborting authentication.
2022-01-25 22:27:13,557|I| Credentials correct, but Gateway requires two-factor authentication.
2022-01-25 22:27:13,558|I| No 2FA handler found. You may define your own 2FA handler or use built-in handlers. See documentation for more.
2022-01-25 22:27:13,558|W| No 2FA code returned. Aborting authentication.
```

If you look at the log, you can see there is only 6 seconds before it requests another 2FA SMS. This is far too fast for me to respond, I'm pretty sure it attempts another log in before I even get the first SMS.

**Expected behavior**
Thinking about it, I may have been mislead by this video, `https://www.youtube.com/watch?v=O1OhiiCx6Ho&t=6s`, looking at the log carefully it implies that login via https://localhost:5000 is not supported any more and I need to setup a 2FA handler. In that case I think ibeam should just stop if no 2FA handler is found rather than looping. It may also be worth updating the core instructions https://github.com/Voyz/ibeam/wiki/Installation-and-startup since they make no mention of 2FA and as far as I can tell it isn't possible to disable it on your account.

**Environment**
IBeam version: 0.4.0-rc5
Docker image or standalone: Docker image
Python version (standalone users only): NA
OS: Ubuntu 20.04

**Comment by Qarj** [comment]
I managed to get up and running by adding these environment variables to the startup 

```
 --env IBEAM_MAX_IMMEDIATE_ATTEMPTS=2 --env IBEAM_TWO_FA_HANDLER=GOOGLE_MSG
```

I think my issue is more around documentation rather than anything else, I just wasn't getting it.

Also the recommended request, `curl -X GET "https://localhost:5000/v1/api/one/user" -k` , to check that it is up and running responds with

```
{
error: "Failed to load countries"
}
```

which isn't very encouraging. 

`curl -X GET "https://localhost:5000/v1/api/portfolio/accounts" -k` returned more positive info for me.

**Comment by Voyz** [comment]
Hey @Qarj thanks for the detailed issue report 👏

Firstly:

> Thinking about it, I may have been mislead by this video, `https://www.youtube.com/watch?v=O1OhiiCx6Ho&t=6s`

While helpful in popularising the usage of IBeam, this video indeed contains misleading information and does not describe how to use IBeam correctly. This video is why IBeam now says:

```
Note that the Gateway log below may display "Open https://localhost:5000 to login" - ignore this command.
```

I've had a short email exchange with its author to clarify and reupload it, but unfortunately it doesn't seem he followed up with anything yet - which is fine, I guess that he's busy or find this of little priority, but keep it in mind when watching it.

> The first time it did this I got around 5 SMS messages with my 2FA code, in a panic I shut down the computer to stop it blocking my account.

Just reaching 2FA shouldn't cause you any lockout situations - although do let me know if it does, and I'll try to make sure this doesn't happen.

> it implies that login via https://localhost:5000 is not supported any more and I need to setup a 2FA handler

Just to clarify - logging manually via `https://localhost:5000` was never supported. This is where that video gets it wrong.

>  In that case I think ibeam should just stop if no 2FA handler is found rather than looping.

This is a great suggestion. I've modified the code and pushed out `voyz/ibeam:0.4.0-rc6` with that modification. Let me know if it works as you expected.

> It may also be worth updating the core instructions `https://github.com/Voyz/ibeam/wiki/Installation-and-startup` since they make no mention of 2FA and as far as I can tell it isn't possible to disable it on your account.

Thanks for the suggestion, however not all accounts are subject to 2FA authentication, or at least not right from the beginning. For that reason, I think that keeping the documentation as it is will make more sense - for `Installation and startup` wiki to describe just the basics, and for the `Two Factor Authentication` section to describe handling the 2FA. With the new logic you suggested - of stopping IBeam when reaching 2FA without a 2FA handler - I think it will suffice, though feel free to disagree with my reasoning here.

> curl -X GET "https://localhost:5000/v1/api/portfolio/accounts" -k returned more positive info for me.

I didn't realise `"https://localhost:5000/v1/api/one/user"` started returning that failed message. I've modified the documentation to suggest using `/api/portfolio/accounts` instead, thanks! 😊

**Comment by Qarj** [comment]
Hi @Voyz , thanks very much for taking the time to look at my issue report!

I've pulled `voyz/ibeam:0.4.0-rc6` and it looks good, I think this will help people just starting out with ibeam since it stops a potential rapid fire of SMS, whether or not it could lock your account or not is something I don't think I'll experiment with :wink: 

I'm really glad I found your project, I was thinking of buying a mobile number through Twilio to use for 2FA, I didn't realise Google Messages was an option, this is a much better approach.

**Comment by Voyz** [comment]
I'm happy to have been able to help you @Qarj! And sure, don't be tempted to test locking out your account. Just in case though - the good news is that they only lock it up for an hour or so, no need to worry too much. And thanks for the kind words, glad that you're enjoying using IBeam! Take care 😊

**Comment by Voyz** [comment]
Hey @Qarj  I'm going to close this issue due to lack of activity. Feel free to reopen it if you'd like to continue the conversation 👍

**Comment by lakshit2808** [comment]
Hey Guys I'm getting the same error, Can anyone just guide me through the right process? Because I have also locked my account due to this issue
