### ISSUE TITLE
Missing Chrome Driver

### ISSUE THREAD

**Issue by elaamrani** [Voyz/ibeam#55]
**Describe the bug**
I would like to change the allowed IPs is clientportal's conf.yaml file. I tried cloning the repo and modifying the code but the chrome driver is missing

**To Reproduce**
Clone repo and run docker build -t 'my_image' Dockerfile

**Expected behavior**
Be able to build a customized image locally 

**Environment**
IBeam version: 0.3.0
Docker image or standalone:
Python version (standalone users only): 3.7
OS: Mac

**Additional context**
NA

**Suggest a Fix**
Add chrome driver or allow to modify allowed IPs

**Comment by Voyz** [comment]
Hey @elaamrani thanks for describing your issue in detail 👍 If what you need is adding allowed IPs, please note that doing so is supported without the need to build your own IBeam image. See the following:

https://github.com/Voyz/ibeam/wiki/Troubleshooting#access-denied
https://github.com/Voyz/ibeam/wiki/Gateway-Configuration

As for the missing chrome driver - that's correct, you need to supply it when building the image. See [CONTRIBUTING](https://github.com/Voyz/ibeam/blob/master/CONTRIBUTING.md#building-a-docker-image) for more. Note that in the version 0.4.0 this will become obsolete.

**Comment by elaamrani** [comment]
Thanks @Voyz, do you know when version 0.4.0 would be pushed to main? Thanks for your help!

**Comment by Voyz** [comment]
No problem, glad I could help 😊 Let me know if you need any more support here 👍

As for ETA on 0.4.0 - I'm waiting for the feedback from its users to see if we're fixing what we're meant to be fixing. It introduces a number of meaningful changes that attempt to stabilise the connection with IBKR, as well as some optimisations. Realistically, it can be another month or two, unless there are more changes requested which will extend that period. The `0.4.0-rc*` images are available publicly, therefore I don't feel the pressure to release it as the official latest image too early in case it would break some functionalities that we'd need to fix again. Is there any reason you'd be waiting for pushing 0.4.0 to main?

**Comment by elaamrani** [comment]
Thanks @Voyz, version 0.4.0 in 'main' branch would mean a stable version. However, I can definitely have a look at it before. Thanks again for your help! Feel free to close the ticket

**Comment by Voyz** [comment]
Gotcha, yes, once we merge it with `main` it would become the latest stable version - hence taking the time to ensure that it is indeed _stable_. Glad to have been of help! 😊 Voy
