### ISSUE TITLE
Accessing API data from allowed IPs in conf.yaml

### ISSUE THREAD

**Issue by elaamrani** [Voyz/ibeam#56]
**Describe the bug**
I am trying to access the gateway using an internal IP (e.g. conf.yaml allows 192.168.*) and when I try 
curl -X GET "https://192.168.0.0:5000/v1/api/one/user 
inside the container I don't get any data

**To Reproduce**
1. Create a container with vow/ibeam:0.3.0 image
2. Connect a Shell Terminal inside the container
2. Try `curl -X GET "https://127.0.0.1:5000/v1/api/one/user" -k` and it works
3. Try `curl -X GET "https://192.168.0.0:5000/v1/api/one/user" -k` and it doesn't work

**Expected behavior**
Receive data from all allowed IPs in conf.yaml

**Environment**
IBeam version: 0.3.0
Docker image or standalone:
Python version (standalone users only): 3.7
OS: Mac

**Additional context**
NA

**Suggest a Fix**
NA

**Comment by Voyz** [comment]
Thanks for describing the issue in detail @elaamrani

> Try `curl -X GET "https://192.168.0.0:5000/v1/api/one/user" -k` and it doesn't work

To understand what is really happening there - what do you mean by _"it doesn't work"_? Can you paste the output of that command?

**Comment by elaamrani** [comment]
Thanks @Voyz, permission denied resulted in connection being refused. The reason for that was that I was actually not permitted to access that IP. Once I got that permission, the connection was established. Issue resolved. Thanks for your help!
