### ISSUE TITLE
Cannot connect when running on a different port than 5000

### ISSUE THREAD

**Issue by jlixfeld** [Voyz/ibeam#66]
**Describe the bug**
I have a process already running on port 5000, so I need to start IBeam on a different port.  When changing the port, I am able to authenticate, but I am unable to connect to the gateway process.

**To Reproduce**
1. Add the following to `docker-compose.yml`:
```
    ports:
      - 8080:8080
```
or
```
    ports:
      - 8080:5000
```

2. Restart container
3. Authenticate
4. curl
```
% curl -X GET "https://localhost:8080/v1/api/portfolio/accounts" -k
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8080 
```

**Expected behavior**
Non-failure

**Environment**
IBeam version: 0.4.0-rc7
Docker image or standalone: Docker
Python version (standalone users only):
OS: macOS 12.2.1

**Additional context**
I have tried to adjust `IBEAM_GATEWAY_BASE_URL=https://localhost:8080` in conjunction with the various port changes, and also tried to change `listenPort: 8080` in `conf.yaml` without any success, and some of these changes break authentication.

**Comment by Voyz** [comment]
Hey @jlixfeld thanks for reporting your issue 👍

I've put down a guide for changing ports: https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#changing-port

To reiterate:

1. Modify `listenPort` value in `conf.yaml`, eg: `listenPort: 8000`
1. Provide environment variable `IBEAM_GATEWAY_BASE_URL` with a URL modified to the port we want to set, eg: `IBEAM_GATEWAY_BASE_URL=https://localhost:8000`
1. Run IBeam, mapping the new port, eg. `docker run -p 8000:8000`

From your comments I'm reasoning that you've already attempted all of that - is that correct? If so, could you please attach [debug logs of IBeam](https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#debugging) so we could analyse what it does once you perform that change?

Thanks! 😊 Voy

**Comment by jlixfeld** [comment]
What I was trying must have been incomplete, because your complete example provided here works perfectly!

Thank you!!

**Comment by Voyz** [comment]
Ah glad to hear @jlixfeld 😊 Happy to have helped!
