### ISSUE TITLE
Which Python Client Are You Using?

### ISSUE THREAD

**Issue by peter6888** [Voyz/ibeam#67]
**Describe the feature**
Requires Python Client Library To Use IBeam

**Expected interaction**
Better integrated with Zipline Trader

**Comment by Voyz** [comment]
Hey @peter6888, I'm sorry but I don't understand your issue or the question you're trying to post - please expand. 

IBeam's Docker image is is currently running on Python 3.7.7

**Comment by peter6888** [comment]
how to trade then? Such as to place the order. I understand when the docker container running, it will automatically login the account, but do you use any client to execute the order? Such as this https://github.com/areed1192/interactive-broker-python-api ?

**Comment by Voyz** [comment]
Gotcha @peter6888  👍 You'd trade using CP Web API like you would using any REST API, for example by using the `requests` library. The one you listed could also be used.

IBeam is only handling keeping the CP Web API Gateway running and authenticated, it doesn't provide a programmatic interface for trading.

**Comment by Voyz** [comment]
Hey @peter6888 I'm going to close this issue due to lack of activity. Feel free to reopen it if you'd like to continue the conversation 👍
