### ISSUE TITLE
New IB Key advertisement breaks login

### ISSUE THREAD

**Issue by JackD111** [Voyz/ibeam#68]
I assume, I'm not the only one with this problem. It seems, IB added a new advertisement for accounts without 2FA, which advertises the IB Key app. It's possible to skip this by pressing the "Continue" button. The advertisement pages appears immediatly after a successfull login and is shown at `https://www.interactivebrokers.co.uk/sso/Dispatcher`

This is what the pages lookes like:
![image](https://user-images.githubusercontent.com/3951120/157406384-4b930fd0-4ee1-46ac-adec-aca4dbd8c39d.png)

The continue button is enabled with a timeout after 2 seconds. 

Based on the JavaScript of the site, it could be possible to set a cookie called `SKIP_IBKEY_PROMO` with value `True` to maybe bypass the whole screen. If this works, it would be easier to just set the cookie in the driver which should allow skipping implementing logic to handle the advertisement.

JS Source for cookie:
![image](https://user-images.githubusercontent.com/3951120/157407809-a4381b3d-10d6-4163-b4d1-0f60f79bfeb8.png)

Once the user presses "Continue", he's navigated normally to the account management pages. This should complete the login as normal.

Here is the HTML of the redirect login page:
[Login.html.txt](https://github.com/Voyz/ibeam/files/8213226/Login.html.txt)

**Comment by JackD111** [comment]
@Voyz  Thanks for the quick update. I just tried the new image version but the advert page is still shown. 

I just validated the cookie functionality with fiddler and the bypass works, if the cookie is set on the `POST /sso/Dispatcher` request.

Dunno if the driver is not correctly passing the cookie or the IB gateway itself is not passing it on or something.

**Comment by DanielHTpg** [comment]
@Voyz Just had a few mins to locally test some code to handle the advert and found a quick way. When the advert page is shown, the login actually already succeeded and the gateway is authenticated.

You can remove the cookie code and change `authenticate.py` trigger check as following
```
            # observe results - either success or 2FA request
            success_present = text_to_be_present_in_element([(By.TAG_NAME, 'pre'), (By.TAG_NAME, 'body')],
                                                            var.SUCCESS_EL_TEXT)
            two_factor_input_present = EC.visibility_of_element_located((By.ID, var.TWO_FA_EL_ID))
            error_displayed = EC.visibility_of_element_located((By.ID, var.ERROR_EL_ID))
            ibkey_promo_skip_displayed = EC.visibility_of_element_located((By.CSS_SELECTOR, 'a.ibkey-promo-skip'))

            trigger = WebDriverWait(driver, var.OAUTH_TIMEOUT).until(
                any_of(success_present, two_factor_input_present, error_displayed, ibkey_promo_skip_displayed))
```
The `ibkey_promo_skip_displayed` check is enough for ibeam to recognize it was a success and continue as authenciated.

Would appreciate if you could add this and update the docker image.

**Comment by Qarj** [comment]
I don't know why, but for me this fix or anything else I tried getting selenium to recognise something on the promo page failed, I'm stumped. In the end I just set `IBEAM_OAUTH_TIMEOUT=150` - after 2 minutes it turns out the promo message times out and you get the client login succeeds message.

**Comment by Qarj** [comment]
Note that I don't think Chrome allows you to set cookies on localhost, or at least it won't work reliably.

**Comment by JackD111** [comment]
@Qarj Have you tried the latest code in the pull request?

**Comment by Qarj** [comment]
@JackD111 No I tried the code in the message from Daniel above...

**Comment by Qarj** [comment]
And I also tried my own code, various different methods on searching for elements or text present, not sure what I was doing wrong. Possibly I've got an invalid version of chromedriver or something, but everything else is working. I decided not to spend hours trying to figure it out, it looks you have it working which is great.

**Comment by Qarj** [comment]
I see, you are waiting for the element to be clickable, nice, I didn't know about that one. I'm using Cypress these days, it is so much easier than Selenium and the documentation is fantastic, so I'm not so good with Selenium any more.

**Comment by JackD111** [comment]
Yeah, the code posted here wasn't complete. You do need to click the "Continue" link for the gateway to properly authenticate. The latest code in the PR solves the promo handling but is not tested yet for accounts that have 2FA enabled and got the promo. But should work in theory for 2FA accounts too.

**Comment by Qarj** [comment]
Ok then, I should give that code a try, for now the long timeout seems to be working for me as a workaround. I was trying to click the `Continue` immediately. Thanks for this fix!

**Comment by JackD111** [comment]
Yeah, clicking it immediatly doesn't work. If you check the JavaScript of the promo site that I attached above, you'll see, that they use a `setTimeout` of 2 seconds after page load to enable the button.

**Comment by JackD111** [comment]
Closing this since #69 has been merged
