### ISSUE TITLE
Add the ability to send the 2FA challenge code to a custom 2FA handler

### ISSUE THREAD

**Issue by hschickdevs** [Voyz/ibeam#75]
Hi there,

I've created a custom 2FA handler that requests the code using Telegram. However, I currently have no way to receive the challenge code, as shown in the image below:

<img width="513" alt="Screen Shot 2022-03-29 at 5 30 19 PM" src="https://user-images.githubusercontent.com/64290193/160717563-d7215a0c-3cf0-4e67-9b71-85144ed0cc6b.png">

I was searching for possible methods to implement this in the code, and I stumbled across this line in the authenticate.py script. 
https://github.com/hschickdevs/ibeam/blob/b4cb89ec5d79c984fdd71f24f53aad582b3e37b2/ibeam/src/authenticate.py#L203

Since the webdriver is already active at this point, would it be possible to send the challenge text as an optional parameter to the handle_two_fa() function if it is detected? 

The ID for the element is id="chlg_SWCR"

**Comment by hschickdevs** [comment]
Or maybe I'm just missing something... Is there currently a way to get this challenge string?

**Comment by hschickdevs** [comment]
I ended up forking the repository and implementing this on my own. Here are the changes that I made for reference:

https://github.com/hschickdevs/ibeam/commit/d747586a313ba8377b03d2ef2859e5c9129787e9

It works well now, and you can optionally receive the challenge string inside of a custom 2FA handler.

**Comment by Voyz** [comment]
That's a great contribution @hschickdevs 👏 Would you consider submitting this as a PR so others can benefit from your method too?
