### ISSUE TITLE
exec user process caused "no suvh file ..." on windows

### ISSUE THREAD

**Issue by LittleLittleCloud** [Voyz/ibeam#76]
**Describe the bug**
as title

![image](https://user-images.githubusercontent.com/16876986/162260953-14ee746c-d78b-486b-84b5-27ac64cbd0a3.png)

**To Reproduce**
- update to latest ibeam image (8631a89c89ab )
- run
-
**Environment**
IBeam version: latest
Docker image or standalone: docker image
Python version (standalone users only):
OS: windows

**Suggest a Fix**
https://davidcasr.medium.com/docker-standard-init-linux-go-211-exec-user-process-caused-no-such-file-or-directory-en-c0cb42edb295

**Comment by Voyz** [comment]
Hey @LittleLittleCloud thanks for reporting this issue and suggesting a fix. I've implemented .gitattributes to address this - good stuff 👍Just updated `latest` and `v0.4.0` tags with the correct line endings. Let me know if that fixes your issue

**Comment by LittleLittleCloud** [comment]
Just test the latest tag and this issue no longer exists! Thanks @Voyz
