### ISSUE TITLE
Support using docker secrets by allowing for secrets to be read from the filesystem

### ISSUE THREAD

**Issue by jimrobinson** [Voyz/ibeam#87]
**Describe the feature**
I suggest that it would be useful to support reading secrets off the filesystem.  This would allow the use of a Docker Swarm to store the encrypted version of the secrets, instead of requiring them to be in an plaintext env.list or exposing them in the process table when using the --env parameters.

**Expected interaction**
Setting a new environment, e.g., IBEAM_SECRETS_SOURCE to 'fs' would then trigger the assumption that the values in IBEAM_ACCOUNT and IBEAM_PASSWORD are filepaths to be read into memory.  By default IBEAM_SECRETS_SOURCE would be 'env' and default to its current behavior, thereby maintaining backward compatibility.

**Possible implications**
Using this feature would require that a person be using docker swarm.  If a user creates docker secrets but has failed to lock their docker swarm, then the swarm decryption key would potentially be available to an attacker.

**Additional context**
Pull Request: https://github.com/Voyz/ibeam/pull/86

**Comment by Voyz** [comment]
Hey @jimrobinson thanks for this great suggestion and for submitting the PR 😊 Appreciate your patience as it took me a while to get back to you on this.

As for 

>Using this feature would require that a person be using docker swarm. If a user creates docker secrets but has failed to lock their docker swarm, then the swarm decryption key would potentially be available to an attacker.

Are we mitigating or warning about this issue in some way?

**Comment by jimrobinson** [comment]
Hi @Voyz,

I hadn't realized you had asked a question here.  I think we do cover the warning in the documentation we came up with.
