### ISSUE TITLE
GCP Secret Manager

### ISSUE THREAD

**Issue by mike-greenmmd** [Voyz/ibeam#88]
Awesome project here!

I'm just getting started with using this library, but I noticed in your .Readme you said:

`We considered providing a possibility to read the credentials from an external credentials store, such as GCP Secrets, yet that would **require some authentication credentials too**, which brings back the same issue it was to solve.`

Is this always true? I am not an expert on Secret Manager, but my understanding is that you **must** use IAM access controls (see [docs here](https://cloud.google.com/secret-manager/docs/access-control)) for Secret Manager to function. If your trading bot is hosted on GCP, and access is properly controlled with IAM throughout, then I fail to see any _additional_ security issues.

Please feel free to correct me if I'm wrong here!
If not, I'd be happy to work on an enhancement for IBeam + Secret Manager.

**Comment by Voyz** [comment]
Hey @mike-greenmmd thanks for the kind words and for checking out IBeam 😊

As for your suggestion - great you bring up this topic to the surface. Please correct me if I'm wrong too, but don't you need to provide a service account credentials (eg a .json file) to be able to access the Secrets Manager?

If it's hosted on GCP it would use the default credentials of the GCP instance, allowing it to access the secrets without providing any input, however that would be a solution which would limit usage of IBeam only to GCP.

Can we get around this somehow?

**Comment by Voyz** [comment]
I'm going to close this issue due to lack of activity. Feel free to reopen if you'd like to continue the discussion 👍 Thanks for participating!
