### ISSUE TITLE
Docker image is not updated

### ISSUE THREAD

**Issue by tal19987** [Voyz/ibeam#89]
First of all, thanks a lot for this project! Works great!

Now, to the issue :)
I get `Access Denied` when trying to run a python client against your docker in K8s.
After checking the `ibeam` image, I saw that the K8s IPs is **not** whitelisted in the pod, but it does whitelisted in the repo.
Can you please build & push the docker image?
Thanks

# Restore issue:
`docker run -it af03be037b66 cat /srv/clientportal.gw/root/conf.yaml | grep -A 6 ips`

# Expected result:
https://github.com/Voyz/ibeam/blob/078c40b794c4f8c2ba361f37b59c9014985aa7a8/copy_cache/clientportal.gw/root/conf.yaml#L25

# Returned result:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/58375349/175555196-f1676677-b19e-4245-962b-491c8dccbfc0.png">

**Comment by Voyz** [comment]
Hey @tal19987, thanks for pointing it out. Just pushed out 0.4.1 with the update, can you check if your issue is fixed

**Comment by Voyz** [comment]
I'm going to close this issue as this issue is solved. Feel free to reopen if you'd like to continue the discussion 👍 Thanks for participating!
