### ISSUE TITLE
How often should the gateway be reconnecting ?

### ISSUE THREAD

**Issue by dedupe1** [Voyz/ibeam#93]
My gateway seems to drop connection every 4-5 hours depending on the time of day and I wanted to check whether this is what others have been experiencing too. This is a painful issue because 2FA with phone alert is not easy to automate and I haven't figured out a way to bypass 2FA for a new user.

**Environment**
IBeam version: 0.4
Docker image

**Additional context**
Initially I was using a VM in Singapore, which had arguably higher latency with the IB servers. I have now migrated my VM to a data center in NJ and am testing stability as we speak.

**Comment by Voyz** [comment]
Hey @dedupe1 thanks for reporting your issue. We don't have any concrete data, but from just reading what people write I conclude that the connection drop period varies for different people. 4-5 hours that you're experiencing doesn't sound too unusual. Setting up an automated way around 2FA may be something you may want to look into: https://github.com/Voyz/ibeam/wiki/Two-Factor-Authentication

**Comment by dedupe1** [comment]
Hi thank you @Voyz , appreciate the response. And obviously this isn't a bug, its more of 'sanity check' for people doing new installs. Hope others share what they see too. 
Here were my updated ping speeds from my US VM . It used to be 200ms from Singapore and now dropped down to ~2ms from the US. I'll report on how frequently I see disconnects after a few more data points:
```
ping api.ibkr.com
PING e126993.a.akamaiedge.net (23.49.248.12) 56(84) bytes of data.
64 bytes from a23-49-248-12.deploy.static.akamaitechnologies.com (23.49.248.12): icmp_seq=1 ttl=56 time=1.45 ms
64 bytes from a23-49-248-12.deploy.static.akamaitechnologies.com (23.49.248.12): icmp_seq=2 ttl=56 time=1.56 ms
64 bytes from a23-49-248-12.deploy.static.akamaitechnologies.com (23.49.248.12): icmp_seq=3 ttl=56 time=1.50 ms
64 bytes from a23-49-248-12.deploy.static.akamaitechnologies.com (23.49.248.12): icmp_seq=4 ttl=56 time=1.56 ms
```

**Comment by Voyz** [comment]
I'm going to close this issue due to lack of activity. Feel free to reopen if you'd like to continue the discussion 👍 Thanks for participating!
