### ISSUE TITLE
No way to log into my paper account

### ISSUE THREAD

**Issue by hchaudhary1** [Voyz/ibeam#96]
**Describe the bug**
My paper and live account have the same user/pass. However, I don't see any way to log into the paper account on the localhost page.

**To Reproduce**
1. Start new install and login to loclhost:5000

**Expected behavior**
A. Some button to switch between paper/live
or
B. Some parameter to select paper-account at login

**Environment**
IBeam version:
Docker image
OS: Linux/Ubuntu 20

**Comment by hchaudhary1** [comment]
Looks like paper account does have a different user/pass available, I can use it to login for paper.

**Comment by Voyz** [comment]
Hey @hchaudhary1 glad to hear you figured it out 👍
