### ISSUE TITLE
How to login the IBKR Paper Trading by using ibeam?

### ISSUE THREAD

**Issue by GG6666** [Voyz/ibeam#97]
How to select Paper Trading, not Live Trading by default, when login IBKR through Client Portal API by using ibeam?

**Comment by stanj98** [comment]
I think the live trading account ID can be specified within the API. Maybe try storing your account id in an env file or try docker instead: https://github.com/Voyz/ibeam/wiki/Advanced-Secrets

**Comment by GG6666** [comment]
In the env file, the IBEAN_ACCOUNT is the Username, not the account ID/number, for IBKR login. IBKR gives an option (Live or Paper) for login. However, in the IBEAM env file, there seems no IBEAN_ACCOUNT_TYPE to specify Live or Paper.

I also tried to switch the Live account to Paper account by calling IBKR API iserver/account, but it doesn't work.

I wish IBEAM can add this feature.

**Comment by GG6666** [comment]
The solution is to use another username for paper trading to login.

**Comment by Voyz** [comment]
hey @GG6666 thanks for reporting your issue, glad to hear you've figured it out 👍 Just to double check in case you made a typo: make sure your env variables read `IBEAM` not `IBEAN` as you've written here 😉

Thanks for participating and suggesting a solution @stanj98 🙂
